apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileserver
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      role: fileserver
  template:
    metadata:
      labels:
        role: fileserver
    spec:
      containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /exports
              name: export-volume
          env:
                  - {name: SHARED_DIRECTORY, value: /exports}
      volumes:
        - name: export-volume
          hostPath:
            path: /home/roderick/experiment-data
            type: Directory
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values:
                    - mongo-shard-1
                    - debugger

---
apiVersion: v1
kind: Service
metadata:
  name: fileserver
  namespace: dev
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: fileserver
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: dev
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fileserver.dev.svc.cluster.local
    path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filestore
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
---
