kind: ConfigMap
apiVersion: v1
metadata:
  name: startup-config
  namespace: dev
data:
  start.sh: |
    echo "Initialising Mongodb with default login users..."
    mongod --bind_ip_all --logpath '/var/log/mongo-initial-boot.log' &
    sleep 3
    mongosh --norc /kickstart/add-user.js
    kill -9 $(ps aux | grep mongod | grep bind_ip_all | awk '{print $2}')

    echo "Starting Mongos..."
    mongos --tlsMode requireTLS --tlsCAFile /kickstart/root-ca.pem --tlsCertificateKeyFile /kickstart/mongos-1-svc.pem --tlsDisabledProtocols=none --configdb 'configServerRS/config-server-svc-1:27019,config-server-svc-2:27019,config-server-svc-3:27019' --clusterAuthMode x509 --bind_ip_all --logpath '/var/log/mongos.log'

    #mongos --configdb 'configServerRS/config-server-svc-1:27019,config-server-svc-2:27019,config-server-svc-3:27019' --bind_ip_all --logpath '/var/log/mongos.log'

    echo "Boot up complete"

  add-user.js: |
    // wait for mongod to be present...
    var conn;

    while(true) {
      try {
          conn = new Mongo('localhost:27017');
        break;
      } catch (Error) {
        print("Caught error!");
        print(Error);
      }
      sleep(100);
    }

    //conn.setReadPref('primary');
    print("Setting up mongdb users...");

    db = conn.getDB('admin').getSiblingDB('$external');

    var outcome = [];
    outcome.push(
        db.runCommand(
        {
          createUser: "CN=config-server-svc-1,OU=ExperimentClients,O=Roderick,O=BBK,L=Southminster,ST=Essex,C=GB",
          roles: [
            {role: 'userAdminAnyDatabase', db: 'admin'},
            {role: 'readWrite', db: 'test'},
            {role: 'clusterAdmin', db: 'admin'}
          ],
          writeConcern: {
            w: 'majority',
            wtimeout: 5000
          }
        }
      )
    );

    outcome.push(
      db.runCommand(
        {
          createUser: "CN=mongos-1-svc,OU=ExperimentServers,O=Roderick,O=BBK,L=Southminster,ST=Essex,C=GB",
          roles: [
            {role: 'userAdminAnyDatabase', db: 'admin'},
            {role: 'readWrite', db: 'test'},
            {role: 'readWrite', db: 'ycsb'},
            {role: 'clusterAdmin', db: 'admin'}
          ],
          writeConcern: {
            w: 'majority',
            wtimeout: 5000
          }
        }
      )
    );

    outcome.push(
      db.getSiblingDB('$external').runCommand(
        {
          createUser: "CN=localhost,OU=ExperimentClients,O=Roderick,O=Outside,L=Southminster,ST=Essex,C=GB",
          roles: [
            {role: 'readWrite', db: 'test'},
            {role: 'readWrite', db: 'mandelbrot'}
          ],
          writeConcern: {
            w: 'majority',
            wtimeout: 5000
          }
        }
      )
    );

    outcome.push(
      db.runCommand(
        {
          createUser: "CN=arnold-pri,OU=ExperimentServers,O=Roderick,O=BBK,L=Southminster,ST=Essex,C=GB",
          roles: [
            {role: 'userAdminAnyDatabase', db: 'admin'},
            {role: 'readWrite', db: 'test'},
            {role: 'clusterAdmin', db: 'admin'}
          ],
          writeConcern: {
            w: 'majority',
            wtimeout: 5000
          }
        }
      )
    );

    printjson(outcome);
  mongos-sharding.js: |
    use admin;


  root-ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIGaDCCBFCgAwIBAgIUOjdu3xyMKjbkBduXAZ4O39djyzwwDQYJKoZIhvcNAQEL
    BQAwgdYxMzAxBgNVBAMMKlJSVCBHZW5lcmFsIFNlcnZpY2VzIENlcnRpZmljYXRl
    IEF1dGhvcml0eTEOMAwGA1UECAwFRXNzZXgxCzAJBgNVBAYTAkdCMSEwHwYJKoZI
    hvcNAQkBFhJydGltbWUwMUBiYmsuYWMudWsxJzAlBgNVBAoMHkJpcmtiZWNrLCBV
    bml2ZXJzaXR5IG9mIExvbmRvbjE2MDQGA1UECwwtU2Nob29sIG9mIENvbXB1dGlu
    ZyBhbmQgTWF0aGVtYXRpY2FsIFNjaWVuY2VzMB4XDTIzMDgyODIwNDYyMFoXDTIz
    MDkyNzIwNDYyMFowgdYxMzAxBgNVBAMMKlJSVCBHZW5lcmFsIFNlcnZpY2VzIENl
    cnRpZmljYXRlIEF1dGhvcml0eTEOMAwGA1UECAwFRXNzZXgxCzAJBgNVBAYTAkdC
    MSEwHwYJKoZIhvcNAQkBFhJydGltbWUwMUBiYmsuYWMudWsxJzAlBgNVBAoMHkJp
    cmtiZWNrLCBVbml2ZXJzaXR5IG9mIExvbmRvbjE2MDQGA1UECwwtU2Nob29sIG9m
    IENvbXB1dGluZyBhbmQgTWF0aGVtYXRpY2FsIFNjaWVuY2VzMIICIjANBgkqhkiG
    9w0BAQEFAAOCAg8AMIICCgKCAgEAqbgRVu6mK/YxOoEOx00dod8F2mx4x0fqn3EC
    TN6TdpM4n1JGnhD3vx1Cj0Qgc0Clm7S2raHn3zdkAawT0S3Hho9Vx4uPbe+/gWoO
    t/10uPQGMVuLDiHsouWQZezsb4Qgvdvf1V0HMsC49nYttW+eI00A54ld88cxb3+D
    54HelfG3i4ij8gGUO2BSu4jxa9JtXxSy81gkrRo6QJMhXjIM5vPY/nBguX5Z9B7b
    5rZLe3IPL4hBWelr3LJN1927vI4SEiLqsPIUoDtxIJbPikP9xx9XnIZCTbR+h8q1
    v8gHTxHai51RgPCHKOfk7AFVBsn0lRNEGLvCtrtwZvwDfV9j8tQtqA9fr2fV4+rY
    Cz93qqmOPWGc2oKbfn2sj9nBTtOYN5N+xGWFOq8Kppczmtzq5x5HtHJ7lV458iJo
    30ndnZ+cmh3ygop81e6CiyHmQaGDkYCZpV1haqO0txxypDKYWILsJq+58PV5RsFj
    MXuiRIKrAJXvaTxXwSCVIS8leVPcT6uHEAvuoD86ng5RhVW0WY9wgZy+JO3jSqJe
    SSDrTfrTDE1sCq26HeweJKX0hmmXrhE5eOPEyYM92MPMw82GuMo3ZqbDAZRs86hf
    0xoDoif5qvCzOhxkFzlK3PMmvKMqO3LjTBpM+733cC8VKuQJVX6OUXU3UWSIS2/+
    8qktML8CAwEAAaMsMCowCQYDVR0TBAIwADAdBgNVHQ4EFgQUTPe3rrRvRBmGhB2o
    fvb0X7f0e20wDQYJKoZIhvcNAQELBQADggIBAJUaBRCYH0f4gyqev2QSfkpgfcJZ
    98QQ+6gupCeLjj6Y83+c0Od0zUUD12b27XtBk3NPFIJO253WCVqZwGH5t6IKV3Vk
    RQ9RjkJY2EIl5A8Eca7/8qjNjEShFBFeR7udqF3uT/qb658RoJrBKVC8sI+zDtPt
    YTfrmdcMe1nPO4Bh+l6VQmnwUe4Sn2teo7FQGyZ4MxDxKATsNM2MFynmxryjMG8U
    8PpeMLvyxlEQkk9jMgQ3Q+ykd4+83OYj2vcs1hkMcWdBC2USgtvASnhWWfz0wcy+
    aPA7iJxL5hvyiHEMD/WS0bIJpnGMF7NqpXUFSVI7bHj1om1FO7zgozc+mBzqZg5p
    rjGOWMG2Xy1yw+Hbc/FHDVjo9NOC/i5Wsnxu3OmOICPsAYuxdL0JXsxZoiDXIoIm
    R94lQTCB+zley/Jx91rKvgMAFOXvyIRmNyyXvd19smlzHpNH1walZqUoDcAbJo0n
    yqebr0ErbB1Stmd90bSP//FYoZUo4eEC5bx7dJQCAy0NmClXkYTKdm73fSNOI444
    kaiwGJqRKpu4EBT27pyEHL2b2FsNGRZPx578BsC+dU39JfErwUc7sflNeHBRcIXT
    dlmHZfP3YK7GHIphLYEjgZ8lgM1WAWro6S6Q2rCmmHfEjEqP/KjqVGqY59ddezrI
    D1g0bcuXA7v70UOz
    -----END CERTIFICATE-----
  mongos-1-svc.pem: |
    -----BEGIN CERTIFICATE-----
    MIIFWjCCA0KgAwIBAgIBFDANBgkqhkiG9w0BAQsFADCB1jEzMDEGA1UEAwwqUlJU
    IEdlbmVyYWwgU2VydmljZXMgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MQ4wDAYDVQQI
    DAVFc3NleDELMAkGA1UEBhMCR0IxITAfBgkqhkiG9w0BCQEWEnJ0aW1tZTAxQGJi
    ay5hYy51azEnMCUGA1UECgweQmlya2JlY2ssIFVuaXZlcnNpdHkgb2YgTG9uZG9u
    MTYwNAYDVQQLDC1TY2hvb2wgb2YgQ29tcHV0aW5nIGFuZCBNYXRoZW1hdGljYWwg
    U2NpZW5jZXMwHhcNMjMwODI4MjA0NzIzWhcNMzMwODI1MjA0NzIzWjCBujEVMBMG
    A1UEAwwMbW9uZ29zLTEtc3ZjMQ4wDAYDVQQIDAVFc3NleDELMAkGA1UEBhMCR0Ix
    ITAfBgkqhkiG9w0BCQEWEnJ0aW1tZTAxQGJiay5hYy51azEpMCcGA1UECgwgIkJp
    cmtiZWNrLCBVbml2ZXJzaXR5IG9mIExvbmRvbiIxNjA0BgNVBAsMLVNjaG9vbCBv
    ZiBDb21wdXRpbmcgYW5kIE1hdGhlbWF0aWNhbCBTY2llbmNlczCCASIwDQYJKoZI
    hvcNAQEBBQADggEPADCCAQoCggEBALYdL09z4A+KDOIqtpdIO30XnwT3aJ7HsqzC
    +ycgbWz9M7YRub87FzT71neqaWrH+COugJz/F1lXx0MdggSnH6uNQVPS6NLB/BTC
    NGrXgwnAgpYyek5kOFpL6IqLKtX+l/vZM/k41rBL7debv1IIUw6qX586SmbKqbJ/
    f38AmvG+I2i9eHaPv7Q8M2ANhV+feIURhkT6hK/cBBSjjT71s9tjxE5N8iHZXh1C
    RE4Go78cpzNDXKl17IFb25nozMwTRjlVz170CAvEQXEcI+jkSvUlk1SfurT8pIdZ
    y/gtmJV6RnDKQ7zVa9EYZVV7lna7j2PqKXGr49HzX+gc2wZ5RikCAwEAAaNNMEsw
    CQYDVR0TBAIwADAdBgNVHQ4EFgQUathypVNJMDmiQWdyH8cS6Ru0wi0wHwYDVR0j
    BBgwFoAUTPe3rrRvRBmGhB2ofvb0X7f0e20wDQYJKoZIhvcNAQELBQADggIBAAA6
    jnNGnPIuIkjCCiszHOMFwUjHqxXermGvHmzbABCDsAn2SEhlKiZ5t2cwQusZGXPU
    K4+KBeRA0WZ065GNdq7PPTNwpoqBm9YI/1aO54iFeVJgTGcZVQNOWPhjDztvsy/D
    wSmpfmYXelRVQtQXj+I32AXIfaOzeFuUx6NSbdE/Y9fp+rgbr78OhwriZLi/TdWz
    slr1pgeQAf1Tf3jS5WNGeIrC/mUxmo7CKu1MmPBI+LtEKSBor57XQW9508Tei57I
    CC0DiVmQsp3c7GU4Y/lk5pyFnMzO1If4EDMmMaqysoqUWQHDzHVIBu3ymUhpOKcs
    +RvraoRDQ35FOqcvgM1Uyo/bzp4Sj8f2H5FFywNizwqED3c7HBsJ+/rvwdB8pwy5
    yyqKNnJeGr8uNml6UXUkAizkLHP39PhSPNQ/h6P8VcSS7n63i4TMOkKENku223w8
    l/xMNLAzI1osE+oHIChEUhETmnj0J/EIGxilud4l35pU7AeKBWwGBfTRROfrIgz9
    8PQQblNlLWB8eckE6XF4ILbTeIlB9oALlu9XUtadbUUd6+ckATTTOd6cC8RrJ8R8
    jUDHVltfJYP6TvQQDoib/b9lFPSVhpDOpKqpaLrQOPb7WzbTEK9trvScswKN7+rY
    wR/0tgZUeWJoEFUA880dwLrOJrCqn2fHDSh6KaGY
    -----END CERTIFICATE-----
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC2HS9Pc+APigzi
    KraXSDt9F58E92iex7KswvsnIG1s/TO2Ebm/Oxc0+9Z3qmlqx/gjroCc/xdZV8dD
    HYIEpx+rjUFT0ujSwfwUwjRq14MJwIKWMnpOZDhaS+iKiyrV/pf72TP5ONawS+3X
    m79SCFMOql+fOkpmyqmyf39/AJrxviNovXh2j7+0PDNgDYVfn3iFEYZE+oSv3AQU
    o40+9bPbY8ROTfIh2V4dQkROBqO/HKczQ1ypdeyBW9uZ6MzME0Y5Vc9e9AgLxEFx
    HCPo5Er1JZNUn7q0/KSHWcv4LZiVekZwykO81WvRGGVVe5Z2u49j6ilxq+PR81/o
    HNsGeUYpAgMBAAECggEACUU5zu94/s2CG6K9Pfz6M0NYL9Ro1dlYT/lSd+LLkzZd
    8yUamaCYTTULLTcGa/4/NFDKIQPOxFhmrzTRtSstPmo/wrS8L5tamdNrf+tV0zGi
    rCLobTRmlnkh/qh4LyHJSpObVNLXAe0xj63Q2swL71WOrdA1sJ8dLZYWL0jAenED
    iBVn0DbX5D5Axkf98eDKeplxkXgiIo6ChlVNaKsP+N6xQPYaq3LwknYEAVvuv1uJ
    rpSScPWQxFlgxbYNAGPOJRNEtshZgabbUiMXy33vErsEws7ULxoKI99PTH1zOO2+
    R3JpQgZgR7BkkS/GIPWgYLvZ9vBr5+97bEdxsCti0QKBgQDVGkjO0TI+hKnUkDV+
    xZ3Cgdcm0bOHDWb0ucr3eX5iO7ERRqdu5fLOwdTKSnmcL6anOLLE/rUBfmw7VNDN
    +oHb/Nhzbz2+5xekUl3P8SyS5vti/yVDkiKXINkZfIOXe9w0nYFTqfim3DkMLuJA
    agqcxDsBnTFWVGOCsQCMBT3NeQKBgQDaxfn4W6h8i9hQSXpyyi262vn6jKvD+10a
    Q20Wprnd4fwu+Z5jRPxD1m2ka4Nt7DtSpJKRFaLoFTd/uiOOe2ibrECZwK/2LDH9
    /WYYwm+Xi420w6n8Dq6QIGE0B0GM+EdGcR2fugfN5p14W2BnHW3EvKdNwOaR875b
    j08v2doCMQKBgH3wcbTgRwxRhLidnS/VhB1udIN5jNq0nfLlVkEY6QsO8d8e3VaZ
    yPxN6v6+Ms6ODrRmuqfXS4uddkM+JcSFVnd3H0hhJqGKmxs+njiE9G3A2jIwTYp4
    c77S59q7Dl3ZElN5/fM+0TdzkLdVgdrFkI4DHkge6Qh3CPQ0vPkDI/opAoGBALUm
    HTey3a5TNYg1b3jBRGBmlXsLI+chqhPnJNsOrvS0/NYAx0+3fZLGaP8uLyPD6dMi
    hmIwIjY96ziN7oc6VIIifVNSo+EY80Q2oGV8Cl7XpTy6j3QwzAZ3aUVlhLevlYUU
    gM0TgwbRIC7aqtZ3Hb873uSZB9Jum37BCXa70rLhAoGAQqjsdUS7KbRBW97pmiR6
    aIY7eZOM3Qx8BpajrwrcOH5RV0yNgz6k2zcgGQt3wezlSdIu/PxzD9gJ8o4Nl5+t
    pC8ORHPht37aacEGKsSfHDDO2ykBnk7i9PvOMHPKgst1GcsBr/ISVthrnlLqpSor
    Kvems9ObZgiko/lYeRsVVrg=
    -----END PRIVATE KEY-----
  config-sever-1.pem: |
    -----BEGIN CERTIFICATE-----
    MIIGMzCCBBugAwIBAgIUAJmunazewadYYlIMPXN3irhQwuUwDQYJKoZIhvcNAQEL
    BQAwaTELMAkGA1UEBhMCVUsxDjAMBgNVBAgMBUVzc2V4MRUwEwYDVQQHDAxTb3V0
    aG1pbnN0ZXIxDDAKBgNVBAoMA0JCSzERMA8GA1UECgwIUm9kZXJpY2sxEjAQBgNV
    BAMMCUNBLVNJR05FUjAeFw0yMzA4MjQxMDA4MDhaFw0zMzA4MjExMDA4MDhaMIGP
    MQswCQYDVQQGEwJVSzEOMAwGA1UECAwFRXNzZXgxFTATBgNVBAcMDFNvdXRobWlu
    c3RlcjEMMAoGA1UECgwDQkJLMREwDwYDVQQKDAhSb2RlcmljazEaMBgGA1UECwwR
    RXhwZXJpbWVudFNlcnZlcnMxHDAaBgNVBAMME2NvbmZpZy1zZXJ2ZXItc3ZjLTEw
    ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCLnZoBTw7YS4UtTaV+nguW
    n1HwNQ46cRZzRIpeDiOlDwICVnXjRi7zyJ9n9b81pcjjDaAK4hPJdvVIC7y1ET6h
    uFq42MaHXQxKn8pyn0dAG3KtMW7rWOck9Awlz3n7NGL/ZIeJrudCUpBWMVWOfugq
    mQCuyC+GNulxYFb5siHflCvimY6ehd+5WTBXE5awAaUCO7zZk96QUmIom9YhCuF9
    QpRGjKKpENrCDzLkNN+me7JbTHqKzJ9sHAts0xrq004ggKxRJOxQs0sW5ReZB2Eb
    5yOV1r57dbb62a0h+wwCdn7yqGSUmbBMQakcHkndEN0Kxr+jQKssgAPdpi21zpKB
    RUJ1ImIBNQZ3vfQtMB69G2jS4ix/Y7p7OMubnh5CN60r1jQHz8GdrdwSg96IoBaG
    IKGh24wbzaZOSWcGxBxThaaB+Ce98abKXgeFIWTO2ADMfhODrg7Dh2Q90xZO+Kx8
    NboPMjZuQ2qyGtsw2FzpO5L/r7LmdrGCi7BL4eidqxFNs8jOEu90fxCIhe2xBcfG
    wLszN/E1KOlzYpBK+xcTedpANs5hjwjVf2D0jOYIrFJwAGKIfGKh+zsJvTmnhtQ9
    WigJeu7YhZ8D0e4075xf4PI7MTrNN7AcgVGZlR8SPoNuH5pW3WUd54X5I7Zg8bno
    03wXbMFyKa9Vmy+vOJTa5QIDAQABo4GrMIGoMB0GA1UdDgQWBBRmySekaEWVi+nb
    GMHBv+WQztQpTTAJBgNVHRMEAjAAMA4GA1UdDwEB/wQEAwIFoDAsBglghkgBhvhC
    AQ0EHxYdT3BlblNTTCBHZW5lcmF0ZWQgQ2VydGlmaWNhdGUwHQYDVR0lBBYwFAYI
    KwYBBQUHAwEGCCsGAQUFBwMCMB8GA1UdIwQYMBaAFMrUDMfmQIdSjRm1hUMfaYAb
    NfOWMA0GCSqGSIb3DQEBCwUAA4ICAQAMj+ke9u1EiBtOFGx+n/FKuFGoX2Lfwxnb
    TqUI+vY5iWuj3sVrNTdydRnvEfsG53icBy+ORCBxAnpD+13v6HvrprXBo6DQNyUk
    DccUwWUT4p/At5QxYTd0oFBsmXvQwt54k2+jQ0++op+4w4A9WA22t8OYEvE0xL5m
    ItyEpkKPQSSxTrsXnxR/SpabIsgS2hNC1ZY4RhRZBrqoZ0JrtevLuwBu0etaPWpE
    SR6X9KTW0Xkl1umi55T8r/m20pFfAIxlsGFa6ylF88JSqPBNEcn2FZmWy7EEdtMT
    ZzHoxad5B1I7Df341GpDgavgN5uWsY6SCT7CfjRUoDJrJmM7fpfhcWelZS6rA3RX
    0OeqwQBajTEZ3dBqIi0Z7u3CHqyHywOcT6kp0x5BFxBFjc5FN61v0u8c3LVeOZA4
    3icTdi32Jost64sAG4+gC95kr4b8f7NkQaTaeOdKjksdO4rGlXJq4JcXB4bcF+1N
    nuTZf1ZyOUyXdivM1LsbZwLLhSbyeoKiUtDesLujkTnLCFRrpOxFQnBoJKJnCOVB
    649EvNnrH9VRgzDJ5oLS1UZpWr/uEOnTAar1WT8zhuLv/leUE5TtJVNCp429yFTZ
    KqTyUyk5o9GCHpAMFLj9qrXbqjP5PWboR2r+sKczB7JBpGR+LXZpJVytuBk74FBj
    Cke2A20tyA==
    -----END CERTIFICATE-----
    -----BEGIN PRIVATE KEY-----
    MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQCLnZoBTw7YS4Ut
    TaV+nguWn1HwNQ46cRZzRIpeDiOlDwICVnXjRi7zyJ9n9b81pcjjDaAK4hPJdvVI
    C7y1ET6huFq42MaHXQxKn8pyn0dAG3KtMW7rWOck9Awlz3n7NGL/ZIeJrudCUpBW
    MVWOfugqmQCuyC+GNulxYFb5siHflCvimY6ehd+5WTBXE5awAaUCO7zZk96QUmIo
    m9YhCuF9QpRGjKKpENrCDzLkNN+me7JbTHqKzJ9sHAts0xrq004ggKxRJOxQs0sW
    5ReZB2Eb5yOV1r57dbb62a0h+wwCdn7yqGSUmbBMQakcHkndEN0Kxr+jQKssgAPd
    pi21zpKBRUJ1ImIBNQZ3vfQtMB69G2jS4ix/Y7p7OMubnh5CN60r1jQHz8GdrdwS
    g96IoBaGIKGh24wbzaZOSWcGxBxThaaB+Ce98abKXgeFIWTO2ADMfhODrg7Dh2Q9
    0xZO+Kx8NboPMjZuQ2qyGtsw2FzpO5L/r7LmdrGCi7BL4eidqxFNs8jOEu90fxCI
    he2xBcfGwLszN/E1KOlzYpBK+xcTedpANs5hjwjVf2D0jOYIrFJwAGKIfGKh+zsJ
    vTmnhtQ9WigJeu7YhZ8D0e4075xf4PI7MTrNN7AcgVGZlR8SPoNuH5pW3WUd54X5
    I7Zg8bno03wXbMFyKa9Vmy+vOJTa5QIDAQABAoICABBq23G89K9tjf8KSuQtPIqd
    OHrpGj+4DZ5HWIf/3KQrtB5HQXyUw6+qD0ifxrjNwmYks4WkGRSPNv+eVbXrDbTh
    o1VqNEo1oFzkFl/NKAk7UQxZrEPjg+a+BfGqSJtICT4j+aYwmYQchlmEWp2zgaSE
    smZbJu9+5IuO+xtInaAXYeO3D+THNEws1zjeFlGjF96/3JCvSTQqY92HmbHwAB0F
    J792CSidUUQRmnfoWcZPdGU1BJHuxu5lC9jjqB4l8+FxkBHIqDtDIhjSnqhBjGNG
    FlKn2mVVLcuorim5RivB+GKbd5xbyDXnYLXsP95NfdinD2DomVhVw16cjHJ9FJAP
    ePa3oI714M5t1whA6LuZ4OSyPyV3mXq4PVaF3PW2DDgUKcmXT18aoLY+OY3u00F4
    AzaGDTt+eYh9KwnVsMZW56EOjETSVifMsbqhkPIFQdEvNL2UUO46FXAWnY2Q10gI
    gUxhCQJf1Gg0kKLwJ6VdvJRVQKnDLZo7R5S5/jDAwjph7ybhIMstGKBKdfVCTD2K
    a/AmKohByx/nNONh/kqmc5Dgg65YJxDT0CGkQhjGD86yZYCR5+xIiL0ZhNoK+jdp
    Ayg4N843rR4OqGTziEtk+sfzaPh3RT/K9AYpIUZSNbJefsrDTic9W32GSAFhqyaf
    Pa3bokx9zLqVuNz9WXdvAoIBAQC9cE64CiyFleLT+KiqkqsA1nsgvmWWT2zlMsFv
    /3low+l/3/cy8RGV5AcC6zqeFFp8jXV6kqxKkta9BDxqfmCvrHVySmMCtAkfSoVC
    uvzxCJUDpA5LiERoRlMXALnH3rLh1okxhbtlxWoBc0o6KuKXplnDcLn9Zke2gVgb
    8O8lxWHhKxq72vJzm9KTnwcWE40FDxKmpF0it1Gvf/41M8yiVDJTRZkVyGEodKWr
    eqN+AX8vWC203GdPyLBSPwHTDOKnaN0K5Y4n9YhXAlCNzvVnOOuWCjeG5+aPaDS/
    vXTLSGyfTSLJvCEByp+whdTDFr5iso3bpKcSQMOWvieT/Kk3AoIBAQC8q8rx1UMB
    uvK8Qhq0ldYwrcuq6bvVyoQUYUTFtuPym2PonIXnkxhxVVgO7xSo5JzXZUrQoWvN
    HqEyrYhNvNdKpFRNe1CEDRwA6tSb9Sg23bGKJnvxlNh6uoVVM4X/IV5v3VC99SHa
    2I21wUaTvs5fKdnurv9q+yi7gvZP5PRuYFRSyg3Aj3T6Eo2duWNjTh3XMd0HzUlb
    ClQ/UeulOl8VXqVdC+KsEBJysf6C9EWZ7O1a5Dh773WzZt4mu5za6xnyhkMhUt9A
    s2gwA85TxqRIlmrBk50j4LUZdvOeeRGu0wMW3CsN/8Uwcx6HDa3cND0ldC25K0XD
    1Gf7D5gUQrrDAoIBAAtHaohuoqP5fp3cSj6NqPzNyFr0uxut8u/ai8XdUh84uuhQ
    L2mrDL796qTz2HOdBp4v1fTMUtHF2F88p1Q33g3XmM6LO0Xn7jsctr54X6MCPc0P
    sYIxxNDojv3pnyYVTlU/7r8yFSxECsG3WY4JC6C32NRYG9rIgjCNlu9i8vouvFsp
    s9fHe3QCrRD5APUBiP3qHdQqKRluDMEEP+BvCxoHJU/r7udrHM3J1CtXi/BuqmHp
    QB9qmAQaENV0xukH9V6+UZrafBJI/isgCifHULkqnGw8g33WxNV5ANsBrriDwWPi
    tdWJC/YNWGCsNzS+X+uEcgnHzeK6VGrfO4AGJRUCggEAdntb4yqN/dQtA1Rv+N/v
    tnot4JMPxl57O2EqEw+bbotu3nENFjQlsWZq+lXhn36RkCKoLQRx8ko96NlZM5hX
    iyRPXKkIEyU4ZMsT4Sy/qFToXV11kGxs1gW0HaFRkLqf15ggUGpUbF55/530eGvm
    pZReq6lx9Pjsx3SiweGCLp6H1cXVhQuR5kkobdgyNfakfrNtnqyoWGfQKEOFvCk/
    9OeO6TPBkVQ2gZiNwCcuXk+PbvjLD+l8/MCo2aIQCtqBXPA7z/1+/d6smxqIw8uG
    956eRBozIIjIsckljGtzU1poIj75Or1YU+i3TxCkEhksHQ0seZBXK3eEJQHR+0c8
    iQKCAQBK41R1IvOkmeCA+ZOTloMy2vfMDEZmek5rt8MFnlBiNZEveDbm8Gl2c1aK
    e4KKqars1tsMtsCdTWHCJTYduoO30gja9HwnbS5GjnQStJPTEJbpOL++MATi9Plj
    r9KSbDrE2P4NmOieJxz/BOPaif7WxMOHLqpH+/NgJO1ikrij6wQR6eP+LVUpsclb
    f3usqV1z/klwVHqQLJ2Jc/HiHsG2Di+OerpWULDhsDBzXHc0Xfxg/k8ACawXie22
    bTOR9Ojvo3Im6qhhpd3XAyDo8RaDhbHouanvRFe0VO8YqnPZT4Mvkkk+TKzHLnpX
    q4nvUTIOi6pEANErFgTxBYgR2WBQ
    -----END PRIVATE KEY-----
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongos-1
  namespace: dev
  labels:
    purpose: database
spec:
  replicas: 1
  selector:
    matchLabels:
      role:  mongos
      purpose: database
  template:
    metadata:
      labels:
        role: mongos
        purpose: database
    spec:
      containers:
        - name: mongos-1-pod
          image: localhost:32000/mongo-cst:1.0
          imagePullPolicy: Always
          command:
            - 'bin/sh'
            - '/kickstart/start.sh'
          volumeMounts:
            - name: kickstart-dir
              mountPath: /kickstart/
      volumes:
        - name: kickstart-dir
          configMap:
            name: startup-config
      # nodeSelector:
        # kubernetes.io/hostname: rrt-general-services
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values:
                    - mongo-shard-1
                    - debugger

        

---
kind: Service
apiVersion: v1
metadata:
  name: mongos-1-svc
  namespace: dev
  labels:
    purpose: database
spec:
  selector:
    role: mongos
  ports:
    - port: 27017
      targetPort: 27017
  type: LoadBalancer
