kind: ConfigMap
apiVersion: v1
metadata:
  name: startup-config
  namespace: dev
data:
  start.sh: |
    echo "Initialising Mongodb with default login users..."
    mongod --bind_ip_all --logpath '/var/log/mongo-initial-boot.log' &
    sleep 3
    mongosh --norc /kickstart/add-user.js
    kill -9 $(ps aux | grep mongod | grep bind_ip_all | awk '{print $2}')

    echo "Starting Mongos..."
    mongos --tlsMode requireTLS --tlsCAFile /kickstart/root-ca.pem --tlsCertificateKeyFile /kickstart/mongos-1-svc.pem --tlsDisabledProtocols=none --configdb 'configServerRS/config-server-svc-1:27019,config-server-svc-2:27019,config-server-svc-3:27019' --clusterAuthMode x509 --bind_ip_all --logpath '/var/log/mongos.log'

    #mongos --configdb 'configServerRS/config-server-svc-1:27019,config-server-svc-2:27019,config-server-svc-3:27019' --bind_ip_all --logpath '/var/log/mongos.log'

    echo "Boot up complete"

  add-user.js: |
    // wait for mongod to be present...
    var conn;

    while(true) {
      try {
          conn = new Mongo('localhost:27017');
        break;
      } catch (Error) {
        print("Caught error!");
        print(Error);
      }
      sleep(100);
    }

    //conn.setReadPref('primary');
    print("Setting up mongdb users...");

    db = conn.getDB('admin').getSiblingDB('$external');

    var outcome = [];
    outcome.push(
        db.runCommand(
        {
          createUser: "CN=config-server-svc-1,OU=ExperimentClients,O=Roderick,O=BBK,L=Southminster,ST=Essex,C=GB",
          roles: [
            {role: 'userAdminAnyDatabase', db: 'admin'},
            {role: 'readWrite', db: 'test'},
            {role: 'clusterAdmin', db: 'admin'}
          ],
          writeConcern: {
            w: 'majority',
            wtimeout: 5000
          }
        }
      )
    );

    outcome.push(
      db.runCommand(
        {
          createUser: "CN=mongos-1-svc,OU=ExperimentServers,O=Roderick,O=BBK,L=Southminster,ST=Essex,C=GB",
          roles: [
            {role: 'userAdminAnyDatabase', db: 'admin'},
            {role: 'readWrite', db: 'test'},
            {role: 'readWrite', db: 'ycsb'},
            {role: 'clusterAdmin', db: 'admin'}
          ],
          writeConcern: {
            w: 'majority',
            wtimeout: 5000
          }
        }
      )
    );

    outcome.push(
      db.getSiblingDB('$external').runCommand(
        {
          createUser: "CN=localhost,OU=ExperimentClients,O=Roderick,O=Outside,L=Southminster,ST=Essex,C=GB",
          roles: [
            {role: 'readWrite', db: 'test'},
            {role: 'readWrite', db: 'mandelbrot'}
          ],
          writeConcern: {
            w: 'majority',
            wtimeout: 5000
          }
        }
      )
    );

    outcome.push(
      db.runCommand(
        {
          createUser: "CN=arnold-pri,OU=ExperimentServers,O=Roderick,O=BBK,L=Southminster,ST=Essex,C=GB",
          roles: [
            {role: 'userAdminAnyDatabase', db: 'admin'},
            {role: 'readWrite', db: 'test'},
            {role: 'clusterAdmin', db: 'admin'}
          ],
          writeConcern: {
            w: 'majority',
            wtimeout: 5000
          }
        }
      )
    );

    printjson(outcome);
  mongos-sharding.js: |
    use admin;


  root-ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIGRjCCBC6gAwIBAgIUBOKhgRHH9XXIpl7ybK2t9fbOT+QwDQYJKoZIhvcNAQEL
    BQAwZjELMAkGA1UEBhMCR0IxDjAMBgNVBAgMBUVzc2V4MRUwEwYDVQQHDAxTb3V0
    aG1pbnN0ZXIxDDAKBgNVBAoMA0JCSzERMA8GA1UECgwIUm9kZXJpY2sxDzANBgNV
    BAMMBlJPT1RDQTAgFw0yMzAyMjExNzQ4NTZaGA8yMDYzMDIxMTE3NDg1NlowZjEL
    MAkGA1UEBhMCR0IxDjAMBgNVBAgMBUVzc2V4MRUwEwYDVQQHDAxTb3V0aG1pbnN0
    ZXIxDDAKBgNVBAoMA0JCSzERMA8GA1UECgwIUm9kZXJpY2sxDzANBgNVBAMMBlJP
    T1RDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAJXNZDJ32tx6y6N4
    /Ph0fRFhHQoT+9TsNW5QqE+M9Z/PIqRiC5oPFIxjJyai/ioNgc0IHz50r5lMHnZg
    18xmx+ebT1FHvHsi+rcuqJAt7yFT6HvA8ih08GpeYfUVawLvJnGAET49U3cq2a9/
    Pks9zRlaGWwP5lzpnHG/0k/GzRLFhI8tpu+t1ZNgn2f6FRrAxXJ6mASjZXJ6RqYf
    mjPMIBt2tiKoU7DoMz/BqvZ9rZL/tAO3s1lWHoyrJ0n/F+ppkKVnGWE3WJpmodqV
    g/ydZIf8Vj0Tqlbv5uZ+c469mvSLCqfZ80o5zn2JD1H4ZvTcZghLSsHLlcoUAz3U
    Det53dyHTvP2SoVXCbk2yxhuYDRnWVx4lx4ORvldiGx5KWMy2C8HQzOxR2fFGzCL
    AfeXNg0P/+YLokOKjVspuyuGalUzHfp+JJPgixg6GkjCkUJPLppr4VfXrpsYgbah
    w6yyfxEvSamKB8RKKHTsF5EeXLLrDsE3j1x+B3slqzxbFIJ6CiIApriSwS/v/zQP
    RNgFm0gUk01T1mrPpmaOrZ8GWphinnKR76Br43A+SMMF2AkGhMxGIrLYLbMN9htR
    ApOeD1MS2jNkjKJo8isVR/unDIVmsjNTTlI/b9eMwmAx/4iVTBa2QHlp0RJAENNb
    X5LR/kR2lW+ZT81TEPzKQNiYJ+OdAgMBAAGjgekwgeYwHQYDVR0OBBYEFKk5cY7a
    eS5RAuPuEPPqs0eUgRLbMA8GA1UdEwEB/wQFMAMBAf8wgaMGA1UdIwSBmzCBmIAU
    qTlxjtp5LlEC4+4Q8+qzR5SBEtuhaqRoMGYxCzAJBgNVBAYTAkdCMQ4wDAYDVQQI
    DAVFc3NleDEVMBMGA1UEBwwMU291dGhtaW5zdGVyMQwwCgYDVQQKDANCQksxETAP
    BgNVBAoMCFJvZGVyaWNrMQ8wDQYDVQQDDAZST09UQ0GCFATioYERx/V1yKZe8myt
    rfX2zk/kMA4GA1UdDwEB/wQEAwIBBjANBgkqhkiG9w0BAQsFAAOCAgEAaBy6YP8q
    vGR7Z6+yBGJj7R/YZxhsZx4NPAP6IfgvTe9ELe7vdVO5AWD3Q8Kq3PlwEEENcfoI
    cuUI2ZVU7axO5TCLVZLPp/eSnGUloXw/hL+8g0J338HSobXQ5Q+M/5rY8NTsHPQL
    OM30WVE/1vr3w14BbLXn+GlSh3aAAg0qJs9YkzFYJa9S12dr7bWzlc8ZMuGesjlr
    Dy0PhceCcgx1pi54TIo1zza5hw9rTXxl7wMJBM9sSR5whGBQm3gksYITjf7nDQdm
    zP6foS2HvdlLBRdOfbmGS9TWv4KgtbCuGq7bAxxJanX4zbjgZfdFUDxnWaX1Z1WT
    cuFk6KqY3LxkvOJOZc3N3FlihTgo8ijOE0k0ddogSIp4ftQczyFR5vXxWpf0v2Ph
    8fFLRjBv3kcJxkt/cNTUARu0spzSAAQKPRBZHC9y0HOVbQqpVsbxjik9+1wyXyv0
    Ur9JlM99nrT9W8t1eShtNrRHWfgV4OK+wvYhn16qGQf/3KojQ6AwTxzjUqQed7XZ
    xN9y3CEAkBTvYn0PiPCRu15bvH43KlmpYh3+YJRJsbqSPRAq+5yr7LJ8SAbiPboh
    7OzmR3YL6MjEzPHS2X1ftAFNjdKg9ubUYdg9nJBVhrhovZBEdf+SKojFG0NhWnP0
    aeK4WPCj1wo6oSCpjxmty2KPACLRWYmm5IM=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIGNjCCBB6gAwIBAgIBATANBgkqhkiG9w0BAQsFADBmMQswCQYDVQQGEwJHQjEO
    MAwGA1UECAwFRXNzZXgxFTATBgNVBAcMDFNvdXRobWluc3RlcjEMMAoGA1UECgwD
    QkJLMREwDwYDVQQKDAhSb2RlcmljazEPMA0GA1UEAwwGUk9PVENBMCAXDTIzMDIy
    MTE3NDg1N1oYDzIwNjMwMjExMTc0ODU3WjBpMQswCQYDVQQGEwJHQjEOMAwGA1UE
    CAwFRXNzZXgxFTATBgNVBAcMDFNvdXRobWluc3RlcjEMMAoGA1UECgwDQkJLMREw
    DwYDVQQKDAhSb2RlcmljazESMBAGA1UEAwwJQ0EtU0lHTkVSMIICIjANBgkqhkiG
    9w0BAQEFAAOCAg8AMIICCgKCAgEAvRIo0bR8fnkeR73A0Wvmw8Vx2uDzAIp7BM5w
    8hDeD5eYi+uRx+Je74TWmYxAeARzex3CZHFONLYH85H2oKBAQqfR4KkxBKcs6R05
    zXPmmmkq7kXDcyzQPozEIdUZEfXyH+8B4tJlBtbP+7wd6CACxRk1hN04AkBHdcvG
    KXescN4k7ne7U2N4dVU+ZMHorLRtBAEJv5BCcu6xse7rmwtCBcWQDZP2aMdMIJY9
    PhkXbQPiew4LhVJCfDGvhe0qEbQrh9heCm99c0oZRMlFDziuv1mUdDu4Wxu39z5V
    9beVN++hGaSk7TbluVsFvzupgN9yAY/0uP1wGEI1eKMwkWQ45DsvRpSHVMMlr8ZX
    B/OLUJwRZ6B2uWNVo4rplmDB92YrTP1DzEpbHfb8FJyweRsSWe4Q06JnV+3RPSt0
    OFI0zqssV0dmbdgbxmlkPlWPKFpPdnPFHh3/lEpUJh4gvZPVM59uKlNXjvXYwh2f
    1NGPibVakJG9jegs8DM45O6WsLVbu9W420cEkhYXMQ9SgY9Lpe/v7sxALMH4ioCZ
    P3mP4ayQ0bPWFeSlAHtZAAdxLBfOFplNhNr56CsgP7vJYXcmH6yjZbiYUreYKY0U
    xZTKgTdZnF63RTDumH0hpkw7c/2dFey6m/4WR/Vgzg79HtYCsIBJMNxBpkLgTXBY
    j8T9SacCAwEAAaOB6TCB5jAdBgNVHQ4EFgQUCy6t0VN/tmszE70JnTBx83VPJOQw
    DwYDVR0TAQH/BAUwAwEB/zCBowYDVR0jBIGbMIGYgBSpOXGO2nkuUQLj7hDz6rNH
    lIES26FqpGgwZjELMAkGA1UEBhMCR0IxDjAMBgNVBAgMBUVzc2V4MRUwEwYDVQQH
    DAxTb3V0aG1pbnN0ZXIxDDAKBgNVBAoMA0JCSzERMA8GA1UECgwIUm9kZXJpY2sx
    DzANBgNVBAMMBlJPT1RDQYIUBOKhgRHH9XXIpl7ybK2t9fbOT+QwDgYDVR0PAQH/
    BAQDAgEGMA0GCSqGSIb3DQEBCwUAA4ICAQAP0nroy+mO93KyZhw1keCQrmuwQWZi
    pI9CKqJlr4ONGviCJCg8BR0iXZs11+5uj9gSd/kd6lh8HNuXQBZGYfpBtXYXWhCU
    7Q7nnPxxI5+uFEYYng+fbL6U1tD/eOSnXXF2a5UaRKhqI8QghE5iRJ6aiYKluM6G
    JEXAuSjIlGOUdFUhNfJO4FrfxPodFcoZd367b8oLitqln8FTw3cOKj7hZXCaUgMw
    /MNIe7kTjkywpqXNpVnHFYeYNFhORoOv+IIi7bOm9XBB9xKfsHIbglxLMHGnMyWn
    W4Vag7u/Jo2CpTARZvkPoKHJBiAXHElDrlrvbKWhZjPdJpM8w3TigNlfQwIcs8Gx
    t2mWYf9Qpv5Sm0ls+/2Sf5jnq00TZcy+iX51a9Bp6JK48dqoGccyfS4RIiJSDT+t
    +35wsNhmhrp7KdDo0Lum+ThArmdAkSDxq1veWMKbxPpxWkED61T+0CluuCkQ2ky2
    cZcFmGetiOyeKk+sVQHhICdaNcpb7xsmk4P48FGXNkJIJPk9d/YwNjNzOzwjsHgS
    tILBaRqgNTBLYLIaOeqs6oFflGWGg5LbF8ghYJJuLsWagyaQwOqbXB6gw4t38q2I
    98dW7LfCIjomb7M2LmzJ3qr3vzvHQeN+uDDrdwUzkFMybP9Opx2z0xJyTXEk81sQ
    UGm4BD588nTDWQ==
    -----END CERTIFICATE-----

  mongos-1-svc.pem: |
    -----BEGIN CERTIFICATE-----
    MIIGLjCCBBagAwIBAgIUeAwjXrBrJN02QeBOv4Fek3x3bmswDQYJKoZIhvcNAQEL
    BQAwaTELMAkGA1UEBhMCR0IxDjAMBgNVBAgMBUVzc2V4MRUwEwYDVQQHDAxTb3V0
    aG1pbnN0ZXIxDDAKBgNVBAoMA0JCSzERMA8GA1UECgwIUm9kZXJpY2sxEjAQBgNV
    BAMMCUNBLVNJR05FUjAgFw0yMzAyMjExNzQ5MDVaGA8yMDYzMDIxMTE3NDkwNVow
    gYgxCzAJBgNVBAYTAkdCMQ4wDAYDVQQIDAVFc3NleDEVMBMGA1UEBwwMU291dGht
    aW5zdGVyMQwwCgYDVQQKDANCQksxETAPBgNVBAoMCFJvZGVyaWNrMRowGAYDVQQL
    DBFFeHBlcmltZW50U2VydmVyczEVMBMGA1UEAwwMbW9uZ29zLTEtc3ZjMIICIjAN
    BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAw9mcw5a++gimni8L6cdiLQG6J8DT
    T/5iSD+nVys7yCcT96ISkJVNf/QDhf/V6ZhdfHjKqKu7v0ESk5cfJi+Z0Ek5w/4x
    9xMr5C/nURF4k7HjW/5YigCKqr2y7ooxKXFbnlMo5qT9cmN9KSQ6lj9xokmJVxQY
    fJ3hyZ74QgjVloZe6J9G8cn0XDlBV8waKZ/1L4Iok96yU2BfNZ0ra9kQwGfGex98
    08dyLb8Uc9A8CbXfnlxUH0iu4dOM5QbOjscL8P/HBo00QZexuhtBsYLBndKoNOyt
    5iHwK+erJzAYH/mgLcumh3ZbfH+CrrbHT9uLRjqhCtRmkGdpXY5KnlycF6hlkVhN
    ryeFjDFq9jWEPDuowm86LfutD+6UqG3ZIw7DbBKIigTpkRVKgajAFuEX7zDWyrWp
    QcaB3ts5VQIz6d3QB4L0ThCQGotoiiWdyYlyDgfqGDjEQqiHoyGQAcjYWgMbTm0U
    BkO1iReJBpak3e2CMmenBYTM58eUh25GUB4aJhgNzVajGofgti4ouDHzMJ0ITOEI
    HTxwLft9L1/0Eqzq3gnOr8Q3LtMX6k4y1v3+H40TtoKuNSkay05EnCVzeNeq92bG
    VXECcMPR4yQS06E6fKATh5Pywu1dELviyG2vZuVEkcl4nClTyVEsdgYf8Y/Ozja8
    Ae+eeUpX7ZeDvZMCAwEAAaOBqzCBqDAdBgNVHQ4EFgQUlIb/cBqDZQWcWwJ88/Dn
    Awkfa7YwCQYDVR0TBAIwADAOBgNVHQ8BAf8EBAMCBaAwLAYJYIZIAYb4QgENBB8W
    HU9wZW5TU0wgR2VuZXJhdGVkIENlcnRpZmljYXRlMB0GA1UdJQQWMBQGCCsGAQUF
    BwMBBggrBgEFBQcDAjAfBgNVHSMEGDAWgBQLLq3RU3+2azMTvQmdMHHzdU8k5DAN
    BgkqhkiG9w0BAQsFAAOCAgEABs//AaP41aAf0w2vC5rW3afw3fcEw6jwF81DQkEG
    yg9jaapBoMur6bVNVzwsW4q6KGtRMPHgjvYDcpLzLAw/b6/qoUkjTMOantLFJe8P
    qfcGRJxCkaC1k2eN2QdThdPmVt3BxK/zvo2yzC64JleqMHIM2E0+IP8rW8nL3je1
    v3HE1RgKr779VapFf9AJbIzE9kq/Hnre+3atpAKJV5G2qP5WpSTgSK3QjEdVUYja
    7ybindPM0w+4zWakIbizTzeuXV2Y+hXcx24qxnoZLl05kVkWBT/Cov9kN9MLwOuV
    kvhEGto5nKFg567noF/E0swSERg9B6QK10FZychYp/dBRUwUdWSB/tZXNoYibmc/
    c/mbeMsNOrOtOIHQOCISomIeucaUfw+fgPUthsZj7UCKfjhwRtMKr3zCkxaTWSFa
    h8XpwUaZDfIVfgUfUlm6gBQWagVFB5VJaqiwpZA5d/55AJXYHiI8oETC/JeuX664
    uYogLcEDx+ybjlP+9Go+Z7qteXEX/WKG0kpdqN4thzwCaZzDxUQcHOi97s4O1pi/
    ndWWbW5zlsLQ8pqHzI/qO4CZ73QLmS6nIexWT29jXIZfgClzdW6Gvqwf7/twyuzP
    Nseev1S9vbEs/im+bvviOu2ij/Ygn9LEYDLpvBW4w6uzfhStama/ZdQkjQZCXu7C
    34c=
    -----END CERTIFICATE-----
    -----BEGIN PRIVATE KEY-----
    MIIJRAIBADANBgkqhkiG9w0BAQEFAASCCS4wggkqAgEAAoICAQDD2ZzDlr76CKae
    Lwvpx2ItAbonwNNP/mJIP6dXKzvIJxP3ohKQlU1/9AOF/9XpmF18eMqoq7u/QRKT
    lx8mL5nQSTnD/jH3EyvkL+dREXiTseNb/liKAIqqvbLuijEpcVueUyjmpP1yY30p
    JDqWP3GiSYlXFBh8neHJnvhCCNWWhl7on0bxyfRcOUFXzBopn/UvgiiT3rJTYF81
    nStr2RDAZ8Z7H3zTx3ItvxRz0DwJtd+eXFQfSK7h04zlBs6Oxwvw/8cGjTRBl7G6
    G0GxgsGd0qg07K3mIfAr56snMBgf+aAty6aHdlt8f4KutsdP24tGOqEK1GaQZ2ld
    jkqeXJwXqGWRWE2vJ4WMMWr2NYQ8O6jCbzot+60P7pSobdkjDsNsEoiKBOmRFUqB
    qMAW4RfvMNbKtalBxoHe2zlVAjPp3dAHgvROEJAai2iKJZ3JiXIOB+oYOMRCqIej
    IZAByNhaAxtObRQGQ7WJF4kGlqTd7YIyZ6cFhMznx5SHbkZQHhomGA3NVqMah+C2
    Lii4MfMwnQhM4QgdPHAt+30vX/QSrOreCc6vxDcu0xfqTjLW/f4fjRO2gq41KRrL
    TkScJXN416r3ZsZVcQJww9HjJBLToTp8oBOHk/LC7V0Qu+LIba9m5USRyXicKVPJ
    USx2Bh/xj87ONrwB7555Slftl4O9kwIDAQABAoICAAOYimo+Beu8iUIsli5ae914
    5wjq0UEVBKe3RM8doiaGru4dE4KEaJWWHL3IQ1V36YcOlV35jFXdVvDPHKzo3ZtF
    kVsA7S4JM+i2B1bXUTjuUl0rbCqgfECf8ugj+C6NADXM6L4PW1UIDSb21ifff8bk
    hcBLtf5F9yc/zebACVRWILD40JFePyhD4KEy4KTC5Qh/Gq1KImV+uG08veWEoewM
    qfLBxGk8kg23FFzi4mEXCmHBy3AMt6OBCTxg0HMR3tfebQeOCuza7259tth0HsB9
    5ZrWRIQ4rS/svCeR36eFThLcvBRH22x9Xby26oLpHxGQ3MlOukMh7LYMFdJPv8KR
    M1QLFucg3HtUt9lQyTycBAGzeC34tj3/U9x/h1yLXp7KAEfeRC/3h4GQ88UtF42Z
    pZeEF9sguQj5/v1H6ej8vJoyNiVleIApQb9QRcIStFokDXMqgit5oqmBja6vKMpn
    3BOaApozvkgAOB35MDehY+pe9UW1zip4M8wvii6JeCJp95uKFxOUDl+dGob3HC9B
    md1/wHnJphE4WE1dfVjAqEiH/Zobb0AgouHOp9Rv9T/0PuLfgxfLzBjr8jgVz+JJ
    4V3iShtc0UzI6tPJGK7GX5WJgaJXUIZYAVdfCk3a7l1KqT0KywnJPzSkGnOb8HEP
    kixIdfgI9p2DiKV2NX7tAoIBAQDSZud467TNlfdcUjhw56wFPOJq7ibjztG4UyGI
    0scxKN+BsuXirVUNVztaDM4NanWdTOtWW6w92lVFHoxUlsfjGLbg+250XRXJXqu3
    FYjBdUUsL0ZD6JfmtCEOOc35pqJ1q0lu/2DWLQrbavOvkSRxabhSUlbCwl4xBrPk
    uPa2lfJTTN91BqqB/AoBR8dn6Oted/6PllqCSftEVXsIC/PUYOnQEOiqMQ1WbnaK
    BYQZh4Y0PJJfEbaknZdZJ3kztNmINT3/QjHSjZmWvIgypqY/k2SsqxhoJKhb6Cp8
    jyLucNQnC2DjR4qlLpCS/1ROmZZaEOK7GkAw1bUqSSYHhN4PAoIBAQDuS14ylI4H
    I9eSB5V7WsYyrGxC0wIFp+9TO239lI5qgVPsmT9Qi1oyHc4ESJ78QLGqNwSoutUn
    UjR9nCMtdfvXgponkRw1NrOuGEMPMTMH+5CL6qSUBRMPGNLK8vZGYFHNIxIO7WtO
    9aFczBBtLT7/06SsJ0iJpBMBvHFf/L6AHKb2zg8xrQIbuPCCU+siRtm+ZuR8BhmA
    6g13j6LxJkyKGLrOkZBGVJBm+JKVb9wpqZhzICksF9k7gJWEzEizgmRbdYm5+K7k
    p1jusA3KEfZWbjONy01Lmsj1oqfUbcEm7d59Pq3odKvawszh+EnbETlwUTL2fWyi
    mRpII6dii+w9AoIBAQDRKamNJU0tX5tztO0VGMqCvn8b7DrPF2iXhFT/DwMklMx0
    xGMSkFvQElsXb0lcPuxDfxcpV6MILke8mdzJrsdxtL0BNhMdLPieojW0oXy9TZaB
    kVGZ6t0vZPzDhqWEPKqerbQn20rqQAbeEBnG/FQtRvsNI3vKy60VseMeSt5Arxoi
    w3YVgZX5+JP9p9zNKNjrpgBzv/WkNmXLDetsGW3BQMLPrC+QGYl31gKTvV4QfxDk
    Vx7v0c0vItc1sy8jPvNOHBfQ7X5YIZqBJlWDfPYil6VqngB6b47LJyctgqIoRhQx
    6HbeGt3yzjK9X4TxSnAUg1rSxAryQVGDgwqCSQzzAoIBAQDpidneznLHkpwB1Qbu
    Jw+ZuBw9/Zi8vFI0C0mHvWE6BleeyK4hnQEfntA6qIWQCUNV46fgSYL/j3Q8Kprb
    Qgc4thmob3HqwRqlo8eNCxXNXAHU7nivTK3aHOTx2937KQjid92J3atObjLfxGrQ
    5QgaJ2z6/2D67F9oUyv1+7kjy3Di7x46/CjVzJGB2QbXyAI8tZB18HBsRHZAV/hE
    SNm4efYS3tw74ULIeBMI++EUv87V/Y38Vb8jrqhaxu71ZvQ+IlqBdbTKCSyCeO56
    vNHk8Qn7jGTLlP4gpnG/InWrVnK34ocEC9wlgMbVK8YOObpGVn4Qzul6DXyReMfi
    L+mtAoIBAQDO/dOSGWyfAEwbSCdU+KqG6R7j2HJkuleYPeBUKUVLG0Nfn4sbr4fE
    K8aNwC+De4lPAB1Yg5bYV0PNgua7gFXgRQhInPRw2/eECyyMlTp4xcocpIG3gkGJ
    jiW4X9o21C5DctSEfqfjTx9sJnNEJHe0zoX2GP+SZyodECIrXyy4XrA+jEnaQYIh
    ACMUgwhIW2CGq2EVWlcrvCwSCFTeedPMahTLLo8QErNJpH2vtVPwtbAdfnFyTAad
    YhRMuIv+85dof016wHH31i3aT+ijwDkiAfyAbQJn6hiuk11fNur4zv4puwfCNfUh
    VIBGx7fJNY1exErKvDS1XQmnJRKIEg0i
    -----END PRIVATE KEY-----
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongos-1
  namespace: dev
  labels:
    purpose: database
spec:
  replicas: 1
  selector:
    matchLabels:
      role:  mongos
      purpose: database
  template:
    metadata:
      labels:
        role: mongos
        purpose: database
    spec:
      containers:
        - name: mongos-1-pod
          image: localhost:32000/mongo-cst:1.0
          imagePullPolicy: Always
          command:
            - 'bin/sh'
            - '/kickstart/start.sh'
          volumeMounts:
            - name: kickstart-dir
              mountPath: /kickstart/
      volumes:
        - name: kickstart-dir
          configMap:
            name: startup-config
      # nodeSelector:
        # kubernetes.io/hostname: rrt-general-services
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values:
                    - mongo-shard-1
                    - debugger

        

---
kind: Service
apiVersion: v1
metadata:
  name: mongos-1-svc
  namespace: dev
  labels:
    purpose: database
spec:
  selector:
    role: mongos
  ports:
    - port: 27017
      targetPort: 27017
  type: LoadBalancer
