kind: ConfigMap
apiVersion: v1
metadata:
  name: startup-config
  namespace: dev
data:
  start.sh: |
    echo "Initialising Mongodb with default login users..."
    mongod --bind_ip_all --logpath '/var/log/mongo-initial-boot.log' &
    sleep 3
    mongosh --norc /kickstart/add-user.js
    kill -9 $(ps aux | grep mongod | grep bind_ip_all | awk '{print $2}')

    echo "Starting Mongos..."
    mongos --tlsMode requireTLS --tlsCAFile /kickstart/root-ca.pem --tlsCertificateKeyFile /kickstart/mongos-1-svc.pem --tlsDisabledProtocols=none --configdb 'configServerRS/config-server-svc-1:27019,config-server-svc-2:27019,config-server-svc-3:27019' --clusterAuthMode x509 --bind_ip_all --logpath '/var/log/mongos.log'

    #mongos --configdb 'configServerRS/config-server-svc-1:27019,config-server-svc-2:27019,config-server-svc-3:27019' --bind_ip_all --logpath '/var/log/mongos.log'

    echo "Boot up complete"

  add-user.js: |
    // wait for mongod to be present...
    var conn;

    while(true) {
      try {
          conn = new Mongo('localhost:27017');
        break;
      } catch (Error) {
        print("Caught error!");
        print(Error);
      }
      sleep(100);
    }

    //conn.setReadPref('primary');
    print("Setting up mongdb users...");

    db = conn.getDB('admin').getSiblingDB('$external');

    var outcome = [];
    outcome.push(
        db.runCommand(
        {
          createUser: "CN=config-server-svc-1,OU=ExperimentClients,O=Roderick,O=BBK,L=Southminster,ST=Essex,C=GB",
          roles: [
            {role: 'userAdminAnyDatabase', db: 'admin'},
            {role: 'readWrite', db: 'test'},
            {role: 'clusterAdmin', db: 'admin'}
          ],
          writeConcern: {
            w: 'majority',
            wtimeout: 5000
          }
        }
      )
    );

    outcome.push(
      db.runCommand(
        {
          createUser: "CN=mongos-1-svc,OU=ExperimentServers,O=Roderick,O=BBK,L=Southminster,ST=Essex,C=GB",
          roles: [
            {role: 'userAdminAnyDatabase', db: 'admin'},
            {role: 'readWrite', db: 'test'},
            {role: 'readWrite', db: 'ycsb'},
            {role: 'clusterAdmin', db: 'admin'}
          ],
          writeConcern: {
            w: 'majority',
            wtimeout: 5000
          }
        }
      )
    );

    outcome.push(
      db.getSiblingDB('$external').runCommand(
        {
          createUser: "CN=localhost,OU=ExperimentClients,O=Roderick,O=Outside,L=Southminster,ST=Essex,C=GB",
          roles: [
            {role: 'readWrite', db: 'test'},
            {role: 'readWrite', db: 'mandelbrot'}
          ],
          writeConcern: {
            w: 'majority',
            wtimeout: 5000
          }
        }
      )
    );

    outcome.push(
      db.runCommand(
        {
          createUser: "CN=arnold-pri,OU=ExperimentServers,O=Roderick,O=BBK,L=Southminster,ST=Essex,C=GB",
          roles: [
            {role: 'userAdminAnyDatabase', db: 'admin'},
            {role: 'readWrite', db: 'test'},
            {role: 'clusterAdmin', db: 'admin'}
          ],
          writeConcern: {
            w: 'majority',
            wtimeout: 5000
          }
        }
      )
    );

    printjson(outcome);
  mongos-sharding.js: |
    use admin;


  root-ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIGRjCCBC6gAwIBAgIUXRNirpfSzGpxA1KnYtRR5u0m67EwDQYJKoZIhvcNAQEL
    BQAwZjELMAkGA1UEBhMCVUsxDjAMBgNVBAgMBUVzc2V4MRUwEwYDVQQHDAxTb3V0
    aG1pbnN0ZXIxDDAKBgNVBAoMA0JCSzERMA8GA1UECgwIUm9kZXJpY2sxDzANBgNV
    BAMMBlJPT1RDQTAgFw0yMzA4MjQxMDA3NTVaGA8yMTIzMDczMTEwMDc1NVowZjEL
    MAkGA1UEBhMCVUsxDjAMBgNVBAgMBUVzc2V4MRUwEwYDVQQHDAxTb3V0aG1pbnN0
    ZXIxDDAKBgNVBAoMA0JCSzERMA8GA1UECgwIUm9kZXJpY2sxDzANBgNVBAMMBlJP
    T1RDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMuKi9VxTO/aPLOB
    m6CRK8Xs9mANS6qTWWFE1VRZiW+Y+sRvdw8IDZjuBTEbnYPu/22G9RVHjuOuXKsS
    0cbs/7+Eok+H7A/OJb2bX80k+JADCsWXpC9ACgZTcxiVwc2FFH5Yv+qtFuIm2CYG
    hB1ZglxTmtYmyJP9krghQewsesd1VbzBiRX3gl0Ns7/WBAM/qXjYe1cVf/nm3kN0
    IkRhNXQUrHOsfOVYhT4KqmC7sfd3xku6vU9b/q0fnDRh4NNVkeXa4jZ5R9YSojcz
    9lnMU9cVssuM1k567XX5OZN9xCx6oVV7vB0qDTsJIgjd6WgqJQbzxTSeKXxDOZ5r
    96pN1Ph3dSzzIB69ZW9Qi4WiVp7cuUT6xoPGKFtlqM0pZV76TJ4Byu3gUJXnx+TV
    vSPu6JqX5IhB6efeZnyWkHkBegZytshch3gliP1GEfi2zqzUY10g5UcXQHLftEf3
    F7Yi6PHUgb0t5WFX8bfbukudovdAwdfcmALtbGfJlCwtygF+mOxiASD2fy9j+1/D
    joPDOKc3uyptzWB8rMjybFi7uyYQo3ZwG/salwznEVl/sjm1/k/IvPw4tV66lN3J
    zWBvX5qD9/V0NdE4JvpRFKooEXTXLu/StFUPcl2Gwi3HiKPzFhyBxpFlJGS88UwA
    WxXBzb+sh6lu78lMjGa58r9kqXlXAgMBAAGjgekwgeYwHQYDVR0OBBYEFN26Iunv
    UgSvPxPgIcCiMPgOeeSwMA8GA1UdEwEB/wQFMAMBAf8wgaMGA1UdIwSBmzCBmIAU
    3boi6e9SBK8/E+AhwKIw+A555LChaqRoMGYxCzAJBgNVBAYTAlVLMQ4wDAYDVQQI
    DAVFc3NleDEVMBMGA1UEBwwMU291dGhtaW5zdGVyMQwwCgYDVQQKDANCQksxETAP
    BgNVBAoMCFJvZGVyaWNrMQ8wDQYDVQQDDAZST09UQ0GCFF0TYq6X0sxqcQNSp2LU
    UebtJuuxMA4GA1UdDwEB/wQEAwIBBjANBgkqhkiG9w0BAQsFAAOCAgEAE7Qeyvbd
    Ecvy56PJEIU6gucJw8qgA4BTCSqwmOwl576Xf+asKq7WbZNX2cq78PKufT47AD0c
    K3BnCEMxcc3DzNzV3qMEAr/7R0tunYLK9UIKMHv3hg7vFS5qhDAStcMJLFHxUSv5
    dVAuErJSM5fYWqqPnVbzbDiPBtwypIyUuZrHNIffkDS6iMZT46qIf0tzMEMyBUKK
    gmSehRyvTJqhgQJJoC9HXv1xagiTT47PKeu1Xj1w3TBV3oXJJcXNqGXnytfsK2Ub
    gaOE5Wxl50T6YKErjZV0ZD3qaPdCdMqfCyr40M3Ums1CJ+EsNkvUT7cR+MilP1NV
    TAxntSJX0VElRVpvU9mm/gjOEe8DmLgd2WYZi94/43QDLC6/q4nUYcVYvOhQSuSd
    OOfOYfQUltp8RhUooqUGkXg7X8YMLH0F24Et9EozG5mndRGlLlOqVJnb/vHa4V7/
    PKnDllGlN8liTwlOsUSWOmA9m9vJFnGb0zSdJId3O4yH7OWcIPsauYEwkor1v8GJ
    sMg9iECQR9l9WgsSNc6OMZOvbJO6CvHj3rDEYOKjcZpu4rFCPtDOAwjnqOcjewav
    WvkzwNz509FgKBQRdLxgJ4FQgF6GVEY1glYhchYYTHK0UTuytkWBjuAUzKUqtvp7
    IWHYCoua/Pv0a6VIKz2wVPOWb9gs4uqtlB8=
    -----END CERTIFICATE-----
    -----BEGIN PRIVATE KEY-----
    MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQDLiovVcUzv2jyz
    gZugkSvF7PZgDUuqk1lhRNVUWYlvmPrEb3cPCA2Y7gUxG52D7v9thvUVR47jrlyr
    EtHG7P+/hKJPh+wPziW9m1/NJPiQAwrFl6QvQAoGU3MYlcHNhRR+WL/qrRbiJtgm
    BoQdWYJcU5rWJsiT/ZK4IUHsLHrHdVW8wYkV94JdDbO/1gQDP6l42HtXFX/55t5D
    dCJEYTV0FKxzrHzlWIU+Cqpgu7H3d8ZLur1PW/6tH5w0YeDTVZHl2uI2eUfWEqI3
    M/ZZzFPXFbLLjNZOeu11+TmTfcQseqFVe7wdKg07CSII3eloKiUG88U0nil8Qzme
    a/eqTdT4d3Us8yAevWVvUIuFolae3LlE+saDxihbZajNKWVe+kyeAcrt4FCV58fk
    1b0j7uial+SIQenn3mZ8lpB5AXoGcrbIXId4JYj9RhH4ts6s1GNdIOVHF0By37RH
    9xe2Iujx1IG9LeVhV/G327pLnaL3QMHX3JgC7WxnyZQsLcoBfpjsYgEg9n8vY/tf
    w46DwzinN7sqbc1gfKzI8mxYu7smEKN2cBv7GpcM5xFZf7I5tf5PyLz8OLVeupTd
    yc1gb1+ag/f1dDXROCb6URSqKBF01y7v0rRVD3JdhsItx4ij8xYcgcaRZSRkvPFM
    AFsVwc2/rIepbu/JTIxmufK/ZKl5VwIDAQABAoICADlmGTf4axNqrlqKzsnxlnAK
    +pGsvi1cv0RkZmqSk2TitbkGnAMjqL37RYCLQpjNob+P4vZ8xwljBuQBeyIHfLnU
    G/eko4fzgQYe1l3iMqxeB0Agmt7uRsVw7BC/Trd384cL3Rc/d6gP/z198eza7J2/
    v/brWf4N8L23N0F0a61q4+JGi7OjqGI4dnu/TUNjRRX8qo+s0vm0xvIrwmwZI7tY
    ByfZuSDuHSkZVeHQnIfmgYeiojdKgJ/uvZyyC3Zdd7bjyo5FFmKCv7ckkrDRI8WQ
    a2rmjRr1pJhzz25N9a/7ZxrVuX9Z+AAxe6UXe3ZyCB4VSYQkpBtUU9/en6mpqEhm
    SI7jgwcoADwbmJUs5Z0+952TT5t8goem1x/xV7Dlwm/Ij9idFMmGNWCdZdekiCc0
    CgZBH59fy1TCNzYpWTOP04gIRIAtaA19Q9dfqEi+wfd09sZKbeYAqMBgYraR/Sf/
    z2Y65ripjaotYWLBUlyuZ4EbjJKm16wKrxFbLKI+nKwRLsb7GWbzreYf4kp097TE
    i4DUlKAcrAcxEwQEuzIUJKcmfFMwm76DSI0Gdkq9JEZqi5i42XA4T3LLr/wByLz3
    +qeqpSFGKpSFnrqIL6scdziS0e6RfRg7EHzaAquz+8yFwyAwi9QhNneTbYq2L47F
    gq2sB9+y0IXcL1ni8L2JAoIBAQDUh5qGpvDaWMVSZfo5aJaWn0RJuC7XsPCl8+Yi
    Z625Uyk8/yo9FHau1BDy2f+KXINyJ4SYm5In+rsn/JPlpB/8nznjU1Ooer4qNrnW
    zcZ4+ciF6Km9vnFdvAdZRIlKaQjrN5EuBGMk3seK6EwhxYgqmaRvvYlyAz1w62KW
    NJ+2n7xj3JFxDjLZCxVbcnN6S47Q9cNAwSw5pN8ETCnskxsMjYmaR5sBK2UEgOd6
    GH7aKc+mVBhfyyroUYMeN5UgXFgThW7SOcVTwFCE5DrT1B3st0l4tenHO2nJIoVM
    ESmRsOFmXL+56Xj2LoENDPnai/fFBQ1+LsTWrO0TI+O+j7spAoIBAQD1LEo/n2vi
    /Rfd4GLhT5LtmR57Dz+wNbdX9CNvWszVTPXfmOCqNCDJq1nlxqRJgvV6bKZQEXTo
    YZEjK2ZGYECNY6cawy0D98mWMKHmmEBtVysq1Vdxu1iNCKGsY4KpOkVGWo0KURnJ
    y+6I/rWYl31ifbpcVva8tcmixXIxCF2vP9CTz/5ppIOaPWmjaO3InZ40jhL9vOL/
    LS09tS1hChkq7fO3t2NnYrvPbyYJyw2RbPAEWfRGs3y/Pg3v2zID5EGFo4Ru3+hp
    9gaRCDbidYSRtwqhWclO9xCpLPCJ7zrY+Fl/MSN5fQ2vTT5LfYHuhn4maxfnOvUl
    EOjShykhkqB/AoIBACP0ONkUvuRBZkhVRiqWHfunP/c0uH/2yA9bHpCtd39FqVFP
    XYbtwlI7QA7FgGyY0Afs1Yq3rtcinKzcFu0fgeXLzhA+FYYIFcmwbmn/b9chcqHs
    xWJ7KFSSLbAVXyB+emrIgMAHL/qZ0aoXOGHyN+H1EhNxPiJSl/9VYt1EU8yiY02F
    j/lPTJzZOii5SP3kcGm7WefHhkLOOIhSljkWfdn2y9OUz404GSPU5tQJ9tPThPR/
    f4wdI8ofmA3xm0HZPXE3/pKEAXT0sOp6bdVOKi3UqBJKvBzfWTsUovZGZQDnqooV
    oL3D2JnVLjHWAyLM0QK8oxa4tMYYhRba2HlxeVkCggEASr+nH4CudvUtKqN34jPN
    mw0dAu3iQAoQjQtNJm0rmDivme1VSe88s9+/N9P5UMRRrXKkvjKkTxk4E93uf7Rm
    2fSxBPLOrbAFUPog0lpHAk8aRSPoVi+FTvJ7wEBSnN+8MTf4WlXho+m+HxxxJ0XA
    n5+viumkrmJKSIskRpjDX2P4Zqh6a6ER0pu4sm6SWKDdlC5g0eWd26jdazvqyvQ2
    OiV0MeYCs4mhsxuzIDc9OsJY5yq51Dhy5ye3PhK5TAByjZkODnPLu0qcM+mqOh8U
    PQzue8URIDcpaDrgV12Ntor5VlMX+rlKy9CkFoX8cEmm+nWaQxBxn0xpf45f1vGK
    ZwKCAQEAtxbCS0JF80hK+ZMlW6jHgQ73lIGEgSPJgbXslXLwXZIiVRX0UhkfrLyI
    oDU3wD2EbrgsY4MEDCNMsVTxp3XYIspasAsxXTSVwjvCNMAOw1vHw5Ef1KXKDw7C
    hW77XAAwtlJi/ijajlKUk/+fnQDolx0C0qWiTcMTkC4jYNSMUr8mftcv6RhW+vqu
    X9iR5yGkkTr5emOmel4KU9B4lyXHwZCbT2+8IYqHhhazi2LicqHEFUDLV9Scf8JQ
    eO4GBHVPq0SMqR7lXn1AxBNt/SXIGV3qzUWvztIxMBU8PrOSG7T6PItox6h3lJW0
    s3pR3kntM9Qv4avugd6qmJAQ0fv+ag==
    -----END PRIVATE KEY-----

  mongos-1-svc.pem: |
    -----BEGIN CERTIFICATE-----
    MIIGLDCCBBSgAwIBAgIUSsOtlX6CwYCPshbT+x+LyQWMuvwwDQYJKoZIhvcNAQEL
    BQAwaTELMAkGA1UEBhMCVUsxDjAMBgNVBAgMBUVzc2V4MRUwEwYDVQQHDAxTb3V0
    aG1pbnN0ZXIxDDAKBgNVBAoMA0JCSzERMA8GA1UECgwIUm9kZXJpY2sxEjAQBgNV
    BAMMCUNBLVNJR05FUjAeFw0yMzA4MjQxMDA4MDdaFw0zMzA4MjExMDA4MDdaMIGI
    MQswCQYDVQQGEwJVSzEOMAwGA1UECAwFRXNzZXgxFTATBgNVBAcMDFNvdXRobWlu
    c3RlcjEMMAoGA1UECgwDQkJLMREwDwYDVQQKDAhSb2RlcmljazEaMBgGA1UECwwR
    RXhwZXJpbWVudFNlcnZlcnMxFTATBgNVBAMMDG1vbmdvcy0xLXN2YzCCAiIwDQYJ
    KoZIhvcNAQEBBQADggIPADCCAgoCggIBAKdS6j1+cJJ2mIr7phhmmdtuRfkw8tGj
    MJ6tkX8rJv26Hp79pINjmzJwQJ/4uGmM7pl4ops5U5ywtPgmMnjUs0V/NsJWp+iw
    sJt1AKQ/77Wygm9Vz9mv8Cv95vi1V8dYDm2b7H2ITi3LH1XdDHC3XMAogrSmzhVl
    7WAEvJMuCYAe6IyXQjr0rBG4LGP/0eWmGGAmxKKAjULcmeFCpfadEMEqDJVB6AqP
    qsLYdNJjs8yt8C/OrIYlGyAkHYy0kYriVnvKPaVfgUdY2npEn8mpghgwMxRfHodM
    ZaE+Juvoy4l1YTWh6EHJnO6/Yx8XrIKPE3NNdzaw3j1x9Ol4xe/bCd8+YLstP0Tn
    +JAM6wiI3wUgMY+vGKGTee7M0Fpoaea1GzOCw/TTRc2sIpUAk06cbjcms4IcFqTP
    JLVeYGfm2RRhGgelRBr9JwkFnylifLf3ez471oBVflkrvUtn0jicJc/g1n+CirTa
    ypVrR5VvPcKn9BlJNTNUk0GIky4iR8H98f/T/8Tx4U0a7i4i5ZYqTYbrUqYR61bD
    dm6D46MkroC+Nw2YLjRkRCTxK1IQeetIgSXTeo7ymYCghgSVjVs2RUKl3CN0Ez8Z
    ZLg2IA6Hc3BS14JoZ131tr5KeGET3B1K74yE+HZlkm7iJTshPRLAg+4QZh+69IxL
    O11s6F2BhmLFAgMBAAGjgaswgagwHQYDVR0OBBYEFIgXq6uWTD9ytUypbMkVB2XS
    ho/OMAkGA1UdEwQCMAAwDgYDVR0PAQH/BAQDAgWgMCwGCWCGSAGG+EIBDQQfFh1P
    cGVuU1NMIEdlbmVyYXRlZCBDZXJ0aWZpY2F0ZTAdBgNVHSUEFjAUBggrBgEFBQcD
    AQYIKwYBBQUHAwIwHwYDVR0jBBgwFoAUytQMx+ZAh1KNGbWFQx9pgBs185YwDQYJ
    KoZIhvcNAQELBQADggIBAL5xc/jQB6H5CxGpzNVNKKxsmhws+0pMF8tW8GPep4G+
    /fZ0vMPvMXvsYW7P9rR0bCYTdzyEvFfF5fNZT26gK/aFbp/iOUEfVAOXkOdlcyqJ
    0ky3xAFtBL9juM+dIECXGvPFHT7uxElk+BlaUZx1evn+/degyQe6FugAE+DWSwMi
    ICG2y6DijSxHIEGZ60v4fFjEoZNUUFEu4bNNo3KXj+jpXbP5z6QynC7yWwTDE1yF
    7iU87T+zB3afqat+/UKppNi+t3K/93Ld1pfU5/jx+4TtZ3qxP4at8JP0N+Caz57l
    XVhgxb0geFgGqUhavrFGTyCOps6YNwAp/kcTmdHQX1hyfZRv3DRXU+3TLMtN5Ede
    bWqNd3sk+8+HP8q5Py9akze9sPMGqFd6viqLd+3VwDzAb27h4w0qGjvHAnQvxvOE
    qD5N/dtdRrcCaHxGS0hCEaMLmZFHVDXUPyqcmvGRRBrfdPCXITSjNnqFwkK3SGPF
    kGkur2UasYeUQZnETUDI0vBXIhxDy3lU+wEzmwnRyu02jccCmHCc98TkhaUnxN3d
    nQ1oIybfYhk4uo5QhyM6ZybXpwNJDfQuXpHgp3qH8kz5ZBSXk8SH2aPyhTbqBddg
    35mZcTZCACsJb5G5jY8HtG+6QwD3J30ZVjR6eCM2RiNEjfqmJLoItlT+UlcAqbii
    -----END CERTIFICATE-----
    -----BEGIN PRIVATE KEY-----
    MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQCnUuo9fnCSdpiK
    +6YYZpnbbkX5MPLRozCerZF/Kyb9uh6e/aSDY5sycECf+LhpjO6ZeKKbOVOcsLT4
    JjJ41LNFfzbCVqfosLCbdQCkP++1soJvVc/Zr/Ar/eb4tVfHWA5tm+x9iE4tyx9V
    3Qxwt1zAKIK0ps4VZe1gBLyTLgmAHuiMl0I69KwRuCxj/9HlphhgJsSigI1C3Jnh
    QqX2nRDBKgyVQegKj6rC2HTSY7PMrfAvzqyGJRsgJB2MtJGK4lZ7yj2lX4FHWNp6
    RJ/JqYIYMDMUXx6HTGWhPibr6MuJdWE1oehByZzuv2MfF6yCjxNzTXc2sN49cfTp
    eMXv2wnfPmC7LT9E5/iQDOsIiN8FIDGPrxihk3nuzNBaaGnmtRszgsP000XNrCKV
    AJNOnG43JrOCHBakzyS1XmBn5tkUYRoHpUQa/ScJBZ8pYny393s+O9aAVX5ZK71L
    Z9I4nCXP4NZ/goq02sqVa0eVbz3Cp/QZSTUzVJNBiJMuIkfB/fH/0//E8eFNGu4u
    IuWWKk2G61KmEetWw3Zug+OjJK6AvjcNmC40ZEQk8StSEHnrSIEl03qO8pmAoIYE
    lY1bNkVCpdwjdBM/GWS4NiAOh3NwUteCaGdd9ba+SnhhE9wdSu+MhPh2ZZJu4iU7
    IT0SwIPuEGYfuvSMSztdbOhdgYZixQIDAQABAoICAAUpMzR7DfL9UihW+FdHo8y0
    wCXZZXcF8qt2lq4C48QHofN27lgiW9/9b2A9U9FJoPXvajMEK3PuYRJHvrdUYvXK
    EdSWeKnA0R1mGEg9lk4W/Lkueg8YCC9LLsHhUglfhSDecSRGjA4m/+6Ltz2hZye0
    KWfqDVzWSx1VQeoSjWgUmr9DE5DtuoJYozCl9hVi17WN+1WuvDt1TBBh5wAJRGmH
    nhMzuFKPEhfeDu1Pu0OnCaRUKUKolpFUuWGunYE7CNIWHAlZ0W2RNf9QJWbzsKGZ
    NcNav5IeO2VVOtqj2kiLE2yL88mRh4U3Xe9t/+01mxVTBWW8GxRH30Xh9JKHkGKb
    Q8WVKVwi2BkJtPXwFvrStMth5wWjAvaxz8W9/Xn3Hjfomn0X4nn6z7UBzKH88rjL
    h90Gui/GLs/bT6Vm9J7h/8u9cwCh7DDALoT5PcCV/o6N+eKpSjWSmW51mYi27AoD
    hDKJ45zG2GcK6xufuJXKdb2TmSJ956bVWsgnrHfBPliORxI9Q6+N0g0DIVJobGJF
    oiOctb6m+c1OqoKCAGaimnnie/1RIZNJaiPJwV4jU92K9qfRKJap5s2TUdVCJMQF
    mrsopJZIxn6EIsrbjd6KlJ56XSxxtx2ctoM5N9Bu8QzSQ1EX52wAnxRxtJrJbUdZ
    Q9D6lGrPJfOlRzAEZqWXAoIBAQDoerbw5IL54MW2V1Pvdm/BOyoPTs6zOFHaurwO
    Ef/t9BhT1+W4X9Yplv24EjskKmgCUiSBKW6771aEX+UsrU/VBgZKG12E7JUAPX3f
    YnPrMxsjEaOkGxxll5HepRzqAVNvEgrwQK9qKkep/QLeqyQsudEasGSNV46EToFW
    Ko5Ksto3NokwqRAZNdzcOC7dDAM/XXPigr0Q65qAK6CdKzstG8Bvrcka/XxZpYlv
    +by358aPioYVsF/6N5DSc3P0VF26IB54g3e32FOfGxyCKAZqHVsdQss2nci5kumS
    oRvOzSPDA5+MqiMJIbMkbIEfpeTYt+skA7s4qG0FxRKU7XHDAoIBAQC4QKd1WLLL
    b6HvN3Ok7cyQXiaLoA0AR43G4jvFhPVFgooVCplXu15VE3ue3LmCMwSABVoZ7EuZ
    +bYpWUA++6OtgkWOgHgljrUlhQXVl4m/onn0k3fliYzCTH/bBJdYK1BCH2rX0RcA
    AfmBmYyArUaofS3euyLYUlaZqekdTSQDcqriWI/71fsqeyVBGgjQbms2dWL2SAMT
    aS2g6U5FOzp4aWSpE0XRjtnRiNsdldE86+RSNWeSatP83dl+rnS7I/5OEL6kr+vg
    bKu5A2M0reBrbCD7pSj9KOnvvwngHGM7ImK6DsuE0u9C0GDghfFXrbiBiVw7gK7g
    Gk2eEZQqn0jXAoIBAQCmDJCCexU6GVveo31mOrgT0oh2Kpnk1MNScbJEcoLUmVaO
    /FQuXvV++0P5p7vqVwe3MKi2QLvBLHAlWME+KgQtaYIwiF9BxCGg7ErttUqKohQt
    9jlly596yMn9tv1x/sRzPvXlKK6iK9TIC9ly5daOw6IhaABKHFHFGrWyr+62WA0Z
    BrDyuq6u8xPvj4mZhS0Eo2FUVoFohn/yMDcmS2yXCY1ntz8/MfMRrPT/r+cljDz8
    5bpj33iOJgYg6ynVSDUx7iMVfQGTpMYFjL3OEXyTaqhbvAud1RE7yz1d6AkOquNy
    NTJOrG8d5J4p0/5edoWAbc1cCfY9v78vMdXV3cs1AoIBAErvkKu7HUx75GJELTZg
    uJfmksqql18Luu+uRxz4DEDu7HXOT7tMqvry544euxvm3+epRZHRdpXy51E9yVFU
    SqdgmiVwvmyX87iEt3C9JvrXe74q09J49NR5BG7xGRR02TlrSarokPAh3XYGGwyi
    bGBOOP+jIHLWWf45CmQuYX09f5564mRMDNCkMOyfSAJtRhFqAIulkgqs9i/Bc2HY
    ytj6FERnYDfwX0pG3MbVjbm3Pq7opWz5IapwF+rbzQHni5/4U3DrU4V87QJcDFb6
    eJF38pol+9uqbiphigSpxvnf7EM7jS5CE6ka0qu+Df/Y2XdlhCt3FKh0SikFgTss
    eRUCggEBALIG2pRLF3TmtNebI/YRF+K4uxF/1EvepjvKctk/xOLY7qXbs+6IWQ+P
    F77ZSsmc2LEffTd16G1v1eiNOL6A7sl65Cn5eSKPtGEW3TQ3F6RDa2j85/9EEajp
    /Y0y5YkXIXKYG7YYicQHK1jgMxgseh92oVzrbjbldiQHwbSz6JK4+5wv/Rxq5cel
    XPxdCTIUzEOXTA8dNLq+htGglzLzJw1ABkh6mgF7AyJ1wAzJu2gTIzRxjBhbeM42
    Xg/yV5/Wsz4qu29HkWKXCmH8/+upT0t4n4YbxaX1SrHg0TlDshS9emDuFMqLe8gX
    PIvWPJlvxcf4GUcHc3lB+MU7FgCtj2I=
    -----END PRIVATE KEY-----
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongos-1
  namespace: dev
  labels:
    purpose: database
spec:
  replicas: 1
  selector:
    matchLabels:
      role:  mongos
      purpose: database
  template:
    metadata:
      labels:
        role: mongos
        purpose: database
    spec:
      containers:
        - name: mongos-1-pod
          image: localhost:32000/mongo-cst:1.0
          imagePullPolicy: Always
          command:
            - 'bin/sh'
            - '/kickstart/start.sh'
          volumeMounts:
            - name: kickstart-dir
              mountPath: /kickstart/
      volumes:
        - name: kickstart-dir
          configMap:
            name: startup-config
      # nodeSelector:
        # kubernetes.io/hostname: rrt-general-services
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values:
                    - mongo-shard-1
                    - debugger

        

---
kind: Service
apiVersion: v1
metadata:
  name: mongos-1-svc
  namespace: dev
  labels:
    purpose: database
spec:
  selector:
    role: mongos
  ports:
    - port: 27017
      targetPort: 27017
  type: LoadBalancer
