apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-rs-config-calvin
  namespace: dev
data:
  mongo-rs-config-calvin.js: |
    while (true) {
      sleep(1000);
      var result = rs.initiate({
        _id: "calvin.rs",
        members: [
          {_id: 0, host: "calvin-pri:27018", priority: 2},
          {_id: 1, host: "calvin-sec-1:27018", priority: 1},
          {_id: 2, host: "calvin-sec-2:27018", priority: 1}
        ]
      });
      printjson(result);

      if (result.ok == 1) {
        break;
      }
    }

  mongo-replication-calvin.yml: |
    sharding:
      clusterRole:  shardsvr
    replication:
      replSetName: "calvin.rs"
    net:
      bindIp: "*"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: add-shard-calvin
  namespace: dev
data:
  add-shard-calvin.js: |
    var ok = false;

    while(!ok) {
      sleep(10000);
      var error = sh.addShard(
        "calvin.rs/calvin-pri:27018,calvin-sec-1:27018,calvin-sec-2:27018"
      );

      ok = (error.ok == 1);

      printjson(error);
    }

    print("installing cartToPol fn");

      var out = db.system.js.save({
        _id: 'cartToPol',
        value: function (x, y, width, height) {
            return {
                re: -2 + ((x / width) * 4),
                im: -2 + ((y / height) * 4)
            };
        }
      });

    printjson(out);

    print("installing mandelbrot fn");

    var out = db.system.js.save({
      _id: 'mandelbrot',
      value: function (z, c, iterations) {
          if (iterations == 0) {
              return -1;
          }

          var M = {
              re: ((z.re * z.re) - (z.im * z.im)) + c.re,
              im: (2 * (z.im * z.re)) + c.im
          }

          var M_abs = Math.sqrt((M.re * M.re) + (M.im * M.im));

          if (M_abs > 4.0) {
              return iterations;
          }

          return mandelbrot(M, c, iterations - 1);
      }
    });

    printjson(out);
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apt-config-calvin
  namespace: dev
data:
  app-support-pri.sh: |
    apt update
    apt install -y netcat python3 python3-pip
    pip3 install psutil
    mkdir -p /filestore/data/calvin-pri
    mongod --config /config/mongo-replication-calvin.yml --bind_ip_all --dbpath /filestore/data/calvin-pri &
    for i in {1..60}; do
       sleep 10
       echo 'waiting for calvin-pri:27018 ...'
       if `nc -z calvin-pri 27018`; then
        echo 'setting up mongo rs via calvin-pri ...'
        mongo --host calvin-pri:27018 /config/mongo-rs-config-calvin.js
        echo 'mongo rs configured!'
        break
      fi 
    done
    #python3 /filestore/monitor.py
    cd $HOME
    tar -zxf /filestore/node_exporter-1.0.1.linux-amd64.tar.gz
    ./node_exporter-1.0.1.linux-amd64/node_exporter --web.listen-address=0.0.0.0:9091
  app-support-sec-1.sh: |
    apt update
    apt install -y netcat python3 python3-pip
    pip3 install psutil
    mkdir -p /filestore/data/calvin-sec-1
    mongod --shardsvr --replSet calvin.rs --bind_ip_all --dbpath /filestore/data/calvin-sec-1 &
    cd $HOME
    tar -zxf /filestore/node_exporter-1.0.1.linux-amd64.tar.gz
    ./node_exporter-1.0.1.linux-amd64/node_exporter --web.listen-address=0.0.0.0:9091
  app-support-sec-2.sh: |
    apt update
    apt install -y netcat python3 python3-pip
    pip3 install psutil
    mkdir -p /filestore/data/calvin-sec-2
    mongod --shardsvr --replSet calvin.rs --bind_ip_all --dbpath /filestore/data/calvin-sec-2 &
    cd $HOME
    tar -zxf /filestore/node_exporter-1.0.1.linux-amd64.tar.gz
    ./node_exporter-1.0.1.linux-amd64/node_exporter --web.listen-address=0.0.0.0:9091
  configurator.sh: |
    apt update
    apt install -y netcat
    for i in {1..60}; do
      sleep 1
      if nc -z mongos-1-svc 27017; then
        echo 'Establishing shards'
        mongo mongos-1-svc:27017/admin /scripts/add-shard-calvin.js
        break
      fi
    done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calvin-pri
  labels:
    purpose: calvin-pri
  namespace: dev
spec:
  selector:
    matchLabels:
      purpose: calvin-pri
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
      metadata:
        labels:
          purpose: calvin-pri
      spec:
        terminationGracePeriodSeconds: 5
        volumes:
          - name: startup-config
            configMap:
              name: mongo-rs-config-calvin
          - name: apt-config-calvin
            configMap:
              name: apt-config-calvin
              defaultMode: 0777
          - name: filestore
            persistentVolumeClaim:
              claimName: filestore 
        containers:
          - image: mongo
            name: mongo-db-container
            command:
              - "/bin/sh"
              - "-c"
              - "/apt-config/app-support-pri.sh"
            ports:
              - containerPort: 27018
              - containerPort: 9091
            volumeMounts:
              - name: startup-config
                mountPath: /config/
              - name: apt-config-calvin
                mountPath: /apt-config/
              - name: filestore
                mountPath: /filestore/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calvin-sec-1
  labels:
    purpose: calvin-sec-1
  namespace: dev  
spec:
  selector:
    matchLabels:
      purpose: calvin-sec-1
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        purpose: calvin-sec-1
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - image: mongo
          name: mongo-db-container
          ports:
            - containerPort: 27018
            - containerPort: 9091
          command:
            - "/bin/sh"
            - "-c"
            - "/apt-config/app-support-sec-1.sh"
          volumeMounts:
            - name: apt-config-calvin
              mountPath: /apt-config/
            - name: filestore
              mountPath: /filestore/
      volumes:
        - name: apt-config-calvin
          configMap:
            name: apt-config-calvin
            defaultMode: 0777
        - name: filestore
          persistentVolumeClaim:
            claimName: filestore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calvin-sec-2
  labels:
    purpose: calvin-sec-2
  namespace: dev
spec:
  selector:
    matchLabels:
      purpose: calvin-sec-2
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        purpose: calvin-sec-2
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - image: mongo
          name: mongo-db-container
          ports:
            - containerPort: 27018
            - containerPort: 9091
          command:
            - "/bin/sh"
            - "-c"
            - "/apt-config/app-support-sec-2.sh"
          volumeMounts:
            - name: apt-config-calvin
              mountPath: /apt-config/
            - name: filestore
              mountPath: /filestore/
      volumes:
        - name: apt-config-calvin
          configMap:
            name: apt-config-calvin
            defaultMode: 0777
        - name: filestore
          persistentVolumeClaim:
            claimName: filestore
---
apiVersion: v1
kind: Service
metadata:
  name: calvin-pri
  namespace: dev
spec:
  selector:
    purpose: calvin-pri
  ports:
    - name: mongo
      port: 27018
      targetPort: 27018
    - name: node-exporter
      port: 9091
      targetPort: 9091
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: calvin-sec-1
  namespace: dev
spec:
  selector:
    purpose: calvin-sec-1
  ports:
    - name: mongo
      port: 27018
      targetPort: 27018
    - name: node-exporter
      port: 9091
      targetPort: 9091
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: calvin-sec-2
  namespace: dev
spec:
  selector:
    purpose: calvin-sec-2
  ports:
    - name: mongo
      port: 27018
      targetPort: 27018
    - name: node-exporter
      port: 9091
      targetPort: 9091
  type: ClusterIP
---
kind: Pod
apiVersion: v1
metadata:
  name: calvin-configurator-pod
  namespace: dev
spec:
  containers:
    - name: calvin-configurator-container
      image: mongo
      command: ['/bin/sh', '-c','/apt-config/configurator.sh']
      volumeMounts:
        - name: apt-config-calvin
          mountPath: /apt-config/
        - name: scripts-dir-calvin
          mountPath: /scripts/
  volumes:
    - name: apt-config-calvin
      configMap:
        name: apt-config-calvin
        defaultMode: 0777
    - name: scripts-dir-calvin
      configMap:
        name: add-shard-calvin
  restartPolicy: Never