# This file has been generated dynamically using generate-mongo-config-server-yml.pl, edit that file and re-run.
kind: Namespace
apiVersion: v1
metadata:
  name: dev
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: config-server-1
  namespace: dev
  labels:
    purpose: database
spec:
  replicas: 1
  selector:
    matchLabels:
      role:  config-server-1
      purpose: database
  template:
    metadata:
      labels:
        role: config-server-1
        purpose: database
    spec:
      containers:
        - name: config-server-1-pod
          image: localhost:32000/mongo-cst:1.0
          imagePullPolicy: Always
          command:
            - 'sh'
            - '-c'
            - '/kickstart/mongod-launcher.sh'
          volumeMounts:
            - name: kickstart-dir
              mountPath: /kickstart/
      volumes:
        - name: kickstart-dir
          configMap:
            name: rs-config
            defaultMode: 0777
      # nodeSelector:
      #   role: general-services
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values:
                    - mongo-shard-1
                    - debugger

---
kind: Service
apiVersion: v1
metadata:
  name: config-server-svc-1
  namespace: dev
  labels:
    purpose: database
spec:
  selector:
      role: config-server-1
      purpose: database
  ports:
    - port: 27019
      targetPort: 27019
  type: ClusterIP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: config-server-2
  namespace: dev
  labels:
    purpose: database
spec:
  replicas: 1
  selector:
    matchLabels:
      role:  config-server-2
  template:
    metadata:
      labels:
        role: config-server-2
    spec:
      containers:
        - name: config-server-2-pod
          image: localhost:32000/mongo-cst:1.0
          imagePullPolicy: Always
          command:
            - 'mongod'
            - '--configsvr'
            - '--replSet'
            - 'configServerRS'
            - '--tlsMode'
            - 'requireTLS'
            - '--clusterAuthMode'
            - 'x509'
            - '--tlsClusterFile'
            - '/kickstart/mongos-1-svc.pem'
            - '--tlsCertificateKeyFile'
            - '/kickstart/config-server-2.pem'
            - '--tlsCAFile'
            - '/kickstart/root-ca.pem'
            - '--tlsAllowInvalidCertificates'
            - '--bind_ip'
            - '*'
            # - '--dbpath'
          volumeMounts:
            - name: kickstart-dir
              mountPath: /kickstart/
      volumes:
        - name: kickstart-dir
          configMap:
            name: rs-config
            defaultMode: 0777
          # - '/var/lib/mongod'
          #      nodeSelector:
          #cloud.google.com/gke-nodepool: default-pool
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values:
                    - mongo-shard-1
                    - debugger
      # nodeSelector:
      # role: general-services

---
kind: Service
apiVersion: v1
metadata:
  name: config-server-svc-2
  namespace: dev
  labels:
    purpose: database
spec:
  selector:
      role: config-server-2
  ports:
    - port: 27019
      targetPort: 27019
  type: ClusterIP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: config-server-3
  namespace: dev
  labels:
    purpose: database
spec:
  replicas: 1
  selector:
    matchLabels:
      role:  config-server-3
  template:
    metadata:
      labels:
        role: config-server-3
    spec:
      containers:
        - name: config-server-3-pod
          image: localhost:32000/mongo-cst:1.0
          imagePullPolicy: Always
          command:
            #- 'sh'
            #- '-c'
            #- '/kickstart/mongod-launcher.sh'
            - 'mongod'
            - '--configsvr'
            - '--replSet'
            - 'configServerRS'
            - '--tlsMode'
            - 'requireTLS'
            - '--clusterAuthMode'
            - 'x509'
            - '--tlsClusterFile'
            - '/kickstart/mongos-1-svc.pem'
            - '--tlsCertificateKeyFile'
            - '/kickstart/config-server-3.pem'
            - '--tlsCAFile'
            - '/kickstart/root-ca.pem'
            - '--sslAllowInvalidCertificates'
            - '--bind_ip'
            - '*'
            #- '--dbpath'
            #- '/var/lib/mongod'
          volumeMounts:
            - name: kickstart-dir
              mountPath: /kickstart/
      volumes:
        - name: kickstart-dir
          configMap:
            name: rs-config
            defaultMode: 0777
            #     nodeSelector:
            #cloud.google.com/gke-nodepool: default-pool
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values:
                    - mongo-shard-1
                    - debugger

---
kind: Service
apiVersion: v1
metadata:
  name: config-server-svc-3
  namespace: dev
  labels:
    purpose: database
spec:
  selector:
      role: config-server-3
  ports:
    - port: 27019
      targetPort: 27019
  type: ClusterIP
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kickstart-dir
  namespace: dev
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: 'kickstart-disk'
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kickstart-dir-claim
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  resources:
    requests:
        storage: 10Gi
--- 
kind: ConfigMap
apiVersion: v1
metadata:
  name: rs-config
  namespace: dev
data:
  mongod-launcher.sh: |
    mongod --bind_ip_all &
    #mongo --norc --nodb --tls --tlsCertificateKeyFile /kickstart/config-server.pem --tlsCAFile /kickstart/root-ca.pem /kickstart/add-user.js
    mongosh --norc /kickstart/add-user.js
    killall mongod
    mongod --configsvr \
    --replSet configServerRS \
    --tlsMode requireTLS \
    --clusterAuthMode x509 \
    --tlsClusterFile /kickstart/mongos-1-svc.pem \
    --tlsCertificateKeyFile /kickstart/config-server.pem \
    --tlsCAFile /kickstart/root-ca.pem \
    --tlsAllowInvalidCertificates \
    --bind_ip \*
  add-user.js: |
    // wait for mongod to be present...
    var conn;

    while(true) {
      try {
        conn = new Mongo('localhost:27017');
        break;
      } catch (Error) {
        print(Error);
      }
      sleep(100);
    }

    //conn.setReadPref('primary');

    db = conn.getDB('admin').getSiblingDB('$external');
    outcome = db.runCommand(
      {
        createUser: "OU=School of Computing and Mathematical Sciences,O=Birkbeck,emailAddress=rtimme01@bbk.ac.uk,C=GB,ST=Essex,CN=config-server-svc-1",
        roles: [
          {role: 'userAdminAnyDatabase', db: 'admin'},
          {role: 'readWrite', db: 'test'},
          {role: 'clusterAdmin', db: 'admin'}
        ],
        writeConcern: {
          w: 'majority',
          wtimeout: 5000
        }
      }
    );
    printjson(outcome);

    outcome = db.runCommand(
      {
        createUser: "OU=School of Computing and Mathematical Sciences,O=Birkbeck,emailAddress=rtimme01@bbk.ac.uk,C=GB,ST=Essex,CN=mongos-1-svc",
        roles: [
          {role: 'readWrite', db: 'config'},
        ],
        writeConcern: {
          w: 'majority',
          wtimeout: 5000
        }
      }
    );

    printjson(outcome);
  shard-configdb.js: |
    result = rs.initiate({
      _id: "configServerRS",
      configsvr: true,
      members: [
          { _id: 0, host: "config-server-svc-1:27019", priority: 2 },
          { _id: 1, host: "config-server-svc-2:27019", priority: 1 },
          { _id: 2, host: "config-server-svc-3:27019", priority: 1 }
      ]
    });

    printjson(result);
  waitscript.pl: |
    use Socket;

    $| = 1;

    socket(SOCKET1, PF_INET, SOCK_STREAM, (getprotobyname('tcp'))[2]);
    socket(SOCKET2, PF_INET, SOCK_STREAM, (getprotobyname('tcp'))[2]);
    socket(SOCKET3, PF_INET, SOCK_STREAM, (getprotobyname('tcp'))[2]);

    $waiting = 1;
    while ($waiting) {
      sleep 1;
      print "Attempting to connect...\n";
      
      (
        connect(SOCKET1, pack_sockaddr_in(27019, inet_aton("config-server-svc-1")))
        and connect(SOCKET2, pack_sockaddr_in(27019, inet_aton("config-server-svc-2")))
        and connect(SOCKET3, pack_sockaddr_in(27019, inet_aton("config-server-svc-3")))
      ) or next;

      $waiting = 0;
    }

    close(SOCKET1);
    close(SOCKET2);
    close(SOCKET3);

    printf "Connected!\n";

    print `mongosh --tls --tlsAllowInvalidCertificates --tlsCertificateKeyFile /kickstart/config-server.pem --tlsCAFile /kickstart/root-ca.pem --host config-server-svc-1 --authenticationDatabase '$external' --authenticationMechanism MONGODB-X509 --port 27019 /kickstart/shard-configdb.js `;

    exit(0);
  root-ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIGaDCCBFCgAwIBAgIUeyCYCsYaxPA4Cg7onqTToTxvSMIwDQYJKoZIhvcNAQEL
    BQAwgdYxMzAxBgNVBAMMKlJSVCBHZW5lcmFsIFNlcnZpY2VzIENlcnRpZmljYXRl
    IEF1dGhvcml0eTEOMAwGA1UECAwFRXNzZXgxCzAJBgNVBAYTAkdCMSEwHwYJKoZI
    hvcNAQkBFhJydGltbWUwMUBiYmsuYWMudWsxJzAlBgNVBAoMHkJpcmtiZWNrLCBV
    bml2ZXJzaXR5IG9mIExvbmRvbjE2MDQGA1UECwwtU2Nob29sIG9mIENvbXB1dGlu
    ZyBhbmQgTWF0aGVtYXRpY2FsIFNjaWVuY2VzMB4XDTIzMDgyODIyMzQ0NFoXDTIz
    MDkyNzIyMzQ0NFowgdYxMzAxBgNVBAMMKlJSVCBHZW5lcmFsIFNlcnZpY2VzIENl
    cnRpZmljYXRlIEF1dGhvcml0eTEOMAwGA1UECAwFRXNzZXgxCzAJBgNVBAYTAkdC
    MSEwHwYJKoZIhvcNAQkBFhJydGltbWUwMUBiYmsuYWMudWsxJzAlBgNVBAoMHkJp
    cmtiZWNrLCBVbml2ZXJzaXR5IG9mIExvbmRvbjE2MDQGA1UECwwtU2Nob29sIG9m
    IENvbXB1dGluZyBhbmQgTWF0aGVtYXRpY2FsIFNjaWVuY2VzMIICIjANBgkqhkiG
    9w0BAQEFAAOCAg8AMIICCgKCAgEAwe2LHr9hUrexG+n+4N86I/TVTKOlHeE/K7du
    ZJnO5rIlkNaIj4DKVMg6/ZOdx9Xy7N95wmc1q0zMndjdRi3mzXvOEEJlF+tl4Guw
    OZhwSgATcCezAIXSC+5B9x2MUKx1WKF7rtLqYISh+0COVjW6n/nxzs+b0OprHTqg
    wfAYmvcrZkqoDC538HU4ajHrNgtADvLKsLb/mYsykwGgTg57OuzT1oGAnJ0CL82o
    6xHUrIjFbtHZmEikZQTf7XTtehu2a/3YAji0Mp4taXPye/hkE3HRPHVyYGyR870E
    bfoxO05xZwqHBPeGjIb5G5JqcJ5XhvwpyEZju40lMcAYiOHUQFJpXp5gsbBaoou4
    zZMCiFl/o6jZE/8Bs4dK77dJXgN2MVt1d3bdqccsP8eXqzw592VL9O/Z+zHcqeDz
    Ne05kPPHTxs9CZG3awzTuEt2HCV4CTJMzFmE3+QzTD85yB8tLyMpqOejiQ0uqTPS
    scgbJ8P78waEoI6KMvbewGwUQUei2JF9vcharjkPbe+mrqHRjL5hf7t6qA3RMafm
    lT+iAdK3MJHK7YDmXv5KVpoO7pK5dNDlg4bmmECYrs9WXQXSlSwplbd/fs7OdTqM
    PbYn42/Gv12ufKW7jasWbCMBRa/BPPQj7LZcPU+1Fw1rvgK+shgK0hpu/1xKXB8b
    oaiJTVcCAwEAAaMsMCowCQYDVR0TBAIwADAdBgNVHQ4EFgQU6QRoPQej661M+APJ
    2/f5KQUs/dswDQYJKoZIhvcNAQELBQADggIBAGo4q6mBnHujcsFErlS5bDAUsApf
    B2MORUxJ1kmxUuiSzFk6A+rOWtZEPUr21hOvqAR+Wm5uD6lCTvgYGLtM0na0qj8X
    JIN8kS5l9y1WyHOdNGy97Ybx968sf40j2wDdsgyHSBulGuxFx3AwHGd4n+K/H/Fz
    cOKPWx8CT8tCfxIc7jF//3WwK4r5tZvSyoZrn6g0KWekGzduUbV8uBN8mz1ZkOao
    AwHZym/Oz4k72bjA0ChvpfRS3AG7y9kDt0zRJEgVQbPt5jbiJtRf6z+Chkab7ImT
    5hsUk0RtgmIlin1WBo5Z/4pXJLPtCVOGCrklwChTyofL7eTu9cL7n7KG7fre0QTX
    xnLr8ZMnvfQZ6ADsQaM9PTFH3Z+ObC6YIiHQSqZNBeJxu3EFIa//E2AomDd5Yr1Y
    0qBb/EkAfbO3PlO3eMHG19wTsfNJX24BBFNzyu6dldkZJLhvg5hfZHjI2JoaPOHn
    mDl0jiUCwd9uBtu1umGZMJGHsNy/BSIk78va7BlHpjQOlO4HK9ShkyDUzUXHEbBM
    R0mHxJrZRmaS0yJYXuCRX8Ue3u9Ap+OunKAyVs34KCWeJFTIvDLNx/07cVUL2UG6
    T7nke3Tkw/ZP71Zkt+fApVpbq4vd1OTeqQyObpoqclc3gNuO0MqRRLQHEL3/Xbev
    J70CxzZHPVTBS8tb
    -----END CERTIFICATE-----
  config-server.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCghwZlLxe5EyNV
    E/3meyElTr8BJD9oLaWKMf77kBNxEHwoc4EqR1LGL3OBeUk/92HQ6A7HCPJZ7OWe
    t7TvuvOCFjKYfZW164z8p/CtQg2Fx3HOclgtgU4RCz0cNgokw8Le7BxYXSIKscuk
    0ICG8jNn9ojbnC0yTYtenxEf2t1+DkJM+XAULtsjRwFIVmoNeZPualrBISeNBUQR
    9FJf/mK68om24ZOBv+TDJ//0JBhoyFlpNcbcW0DIwToMSXQaQWioH+qPMg28l1e1
    bPBOYr6uTfmvP9A4Mr5k+duxTM7o6oQg/muPSgoocKcbMxrjO/6yvEoCyU0ifAUy
    fu0/RT1XAgMBAAECggEAAimvkV9wD2NNn5DUY+2Wxbzo3+gQHqQ2zcTcraEEUgqp
    0ZW00NADMn5jLQRoUz9PBxSJVm8tbL6/XUMWYgB/1WndJqbShI/251SP7pWsPvgv
    9VsfCwXp+lrPaPjlbBdjIcPGof4nPkOk/cR9ZtQOk0EEGQlipoHa9dxoy6gUQeWD
    0fn489P8UicnzZuV17QqEHv9d0/nqewuzKXCL92+3/7SRgO4z+RdMaiJKnshCA1H
    cCBfs3DIyKYmpWhmVikEE7ZJN/5NfWfR3s4z3BcUitUJ6TReUSMPTMwQxkS7x3Jr
    sgSNuP7fK63CRGDD4qwBvyqGLwFNDEMPBOhFiEKhEQKBgQDRdvEb4PZ7KVcihQzf
    OEW23fLBhbEk8ZFo8JupX9grO8JsXKEoNpWCvhDwGFIYyxIsa+hEiyPKCANRQPNt
    WecIaWjikxbS97NFv9xksPskKNBk/elg3T0MXNI0HZoU1/raSXVwHGHewH7Vjc8u
    qUEBL35Hc+CB5x5e2Nx9tzIZ/wKBgQDEMNZ7r+dxnw2+pnj1cJkc8uEk4ud26lsA
    3oC3mvyLEa+aEOcsfiP6zTa22SAg540np0A5BWgbAycQpC72EETaYWZ0C1IspceT
    883Q0jALnazpkafAYvfjXCA9qLcP1JMjMQxkPa3Y6LCaI0UdYuP3FZLa+b/mUj0Y
    4PF04sXsqQKBgCD3ARcMHn5fkTEDk3UF3CLdZzkBm1FfGy1SwIy1YsXbD8wR/+Le
    REVhODUw/qqcOu32xYUUCLvg6vS8rhLFlVCDllgiIfNtvC779Ol72Opl6fYa58Gw
    z8zERuigyAEDxJzZ9ruAG/78eHmPac3EIVDYcp04JVsMToFKy9iVHjNtAoGAZavV
    izXGoGhH7DRDXRakEo9/w+jfAQ5EaPfmBsCH/d4Ffbcixjj8ll3A7BMrhkHZMeKH
    8sTthYoltYcQWy5lMDLnsF2pkT+8ZN0lHQHAKlTlJgn4wEfJpQa6IpoLfGWydrtV
    a6FXNaCo3MhIagk0kHiaqWZiX47g4MK5/tQCtDkCgYEAxEcSPXfsV38J2X6Vxe7H
    fixyFVLmXVe8qFH6SgCkm/SDjOmyXHslBfEL2fJSavpczx9QnOq+EyQQzSFX8lBR
    0lh6kxzW5Ag2XUHqCb5yPYMdxGHn5uXQguE3FTlrIEvddhB/FB4kCprcGF3hkGmz
    zRNTmOFe/nRjkLqMQQBHARw=
    -----END PRIVATE KEY-----
  config-server-2.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDAZ8xfv7Lr3gip
    j5qB9KCV1gpTu0tbiBSAsygCvluMAWviTclXc7lAZCEu4hdPUxOjWI3thyLyd2vl
    JziT7cZL3Wxq2ALc8F3w2qpcTg/kzoymLs+m8tnFloKJDBNxfHLFnl0S1f96USru
    gWRQP5C9dSDdoliUhzAmYt9Cu1zRdSWc1Jiw7eTC8fvs+/7QXCDbXgB0AGCFCJIc
    +UXnTUrpXDzbIu9+5W+g8S6ope2QTP2zcgSgRTsK86wvVmnh1aAsGQ9LR/A1oT8B
    z+leMygtKgNedmct5ddDXS+h3xILXXfXwQ+iD8JEvIEi4zgQd3ddvRaYyhZnTohD
    1IpnhjIpAgMBAAECggEAAiDj1OdU/mD9bYrGJcvj/uRYRubahY+y0l2pAqbCcoEN
    hXpg0NPZ58lzyIX9xgXgQL1ZDJijHVWO3wEZEiHeQLaZXXE4TuNl1qVEnzLJ4Dkc
    uzXnXCxxlkr89LEqgeXjiyYeV3gAlITTWcIarvyVCFOEYo9KNZJtSO9tEtrpwvNo
    5v7xdv5SWqrsK7RoEP227f2QIifGsAFhZQRHsduGkg3G1pZQRaqJEJituTNl+f5w
    8NkLAxTT1/e1lTcrVrVNV6xJW6JUBClMadUawxA9e45tmk25/GdIhuY0Q3pBkWDh
    HIHi7ggE3n9o26l1wPo1pvXy59BSw8M1OV2ZavKpFQKBgQDb60vhLokSjzBWB0Gf
    C9iaPgva665cytEi00PvJwGeTq9a4WkfChoyr0XHNFMUZMs1ZoabD6D3CspsjBP3
    IL8FhlePN37MwzDtCEs7AInm4WL9jwTLV9tNLSATvUuGo30sDy5l4hfdIJoSL5lu
    Ef87ERHFngOEUVDEFIQHQHvw4wKBgQDf+OpdIyGb0/e63LJVYyJzTElGeHZwj3eO
    7U9k06NyIzQo0h/pLj29EvOtaVWcTDK11khT+1XnNO5wZH6iHQWjIXkaaVj5m6QG
    At6DOlmdLLxfl+PpeRRzbH2rXYHfksv/BgOAdz9B0yzmoIy7XMLfBSFM04AZS1HP
    SBgXnae6gwKBgEaZd+eXV9vEagEEHVXgqK2Dg6zJAlW5qn/ikKmCvStEGVk0idm0
    FYr155G2w4EFhpLjEg1PbB5CsY89PN+V/JzabtuENkmn09oUUopjduHOs0exFRnu
    X3GcLfMITumvLGzrhrqgZYbQg4WZEElcr7IXnbvyKTDeJe58o5Hsap1/AoGBAL8e
    tT7M370NX/QAp9zdP2SL0GtmGAttIWTBdGJhhrO6/qNmyvw8DUruhSmRHRDGpO8t
    74Jakq89J8qYtsa3ZTwTMDgtdVNqUMkgYagxfo70wboA7ucn/x+PkJ1OqaiSp6jz
    BMH2/++3uDUFA5JOUavlwMjCIilzcFgk+QoN6jbpAoGAcAPID94F96YShL0MTA7H
    GPb3FxPvIgpS+QPNsWHkvJlDkyTmUkTGvz8K9ZiXmITsq0L6z97wDyDEy9z1zuOe
    MHmxYRkSO6So5urGcVMkrsnxRv3jS8gqjGxw5wyvFWlHlBuo0qRLndBxB4wfrUzj
    u1pENQQAjj3NXvbBenpCR4k=
    -----END PRIVATE KEY-----
  config-server-3.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCslGn1mXyUsMsU
    LIrhgpHkrHXnblHJRB4PzhqNJXo4jgwmeIz8qLLaUwqmQgsPQMYZSXzWuYt5ziHY
    K+VIflo3yyvFpU3nq+BLK2Ah5bi7DqJvioiemdLPaPJjWGqm+QI0USuekgTyEoXr
    hErZZftCseDLi26++Stl5F5kywdVBjn5uYOTpfi+5Ekb5QK4g77/SIgCyA6J3TD7
    fM5k/DE7qX3W4FOdvbng5hixm1MOMEYnpB8FNVRoptibdKRvP5xKSL3mRKG93KPK
    Qv9sXFUGH3SWX+dnweH6LgpVF4ao4GrPbhut7gf+iyavJcKuOQxkO5BYM7JkdNAJ
    r8I8qH9RAgMBAAECggEACpl7n+HYmiSjocO8l0OBj2sc5g/LW9JgYEsh1q0dwm8j
    BZKI4j8VlmgxnWrYAAypPhtah1unr92pDCcMst+jzeJ0zUkCWGog4Vey1Kd7KZip
    VwgfV6e4oBQ2Mu4sGsDs0ZFyCDq4ArWAM9S7viTP16r81LOQeTqXikS08XmGI+10
    kxEdaE+dYSOGUeVgs7mENHd//m8YMKabGtL3sdTRbY1arDkS2NTSRQ2a/pFK6+Hz
    Tc5rEL34GUhFCS1gcbpqxtRXAlczeA2eNjZKCW+86BL8dQrDAuvg/a/AZaxN29KV
    coFPfKK7YK3ZBp++MTTGxcDVn4p7T3I81fRBLQJqqwKBgQDCX95B5nCFCnsDKGNz
    1BHlei0+mWwGXnTm8Xx8Pgzr0UE0ulna2vSnLnZ1508428IkgEzTxNh9p/Otn10E
    lP2skv0uH0oFuey2OfRveEGZBA8GO26dBGTvUgIWtBUpMP6Q6aDgEuxSC4u/ytfA
    KmiQCpuouCFMuVV4o/9Ov1hfFwKBgQDjS5sjkRijxSTihJNL2gLUfGw7DYQEihQA
    zuxJJ6eWloGrOErKFwX5XEbdiO4fp8pp4E0+I8BJkPdIyN4/59AqotyRpw9FMi3r
    xcMy/6QT4hn6yuKznPBC5QK+hyHrUdezTt+aZNZl/RiADtX/fI4vK3ctS9Z5bm88
    lpo299JV1wKBgQCBpC16aLc9lPrs5UBH3fc9xhptOSj6qn9wFTrBJyW5Fy1VfME3
    nng1FWE/TFLjindXnxce25jFXoLBl5wT1UfIlZU18PqPDS3bcJYezud5pmJa9sLV
    CTxE/r6T4/KFMb9oadq5+QUTx82i0yjJa7+n6ttdUcosASUHvOIo5KiNawKBgQCT
    nCkvSu6GhOR0WwbRjs6hsgATxa5DyGw/LiKTS7ZxfGLPkCo53gPaMkwvWNrUIgK5
    CZsATPV2kTeWxCRZujEdT1ERIj4vgOwDnxYqi4zCAOdAUPwzCyuZNeK3W0jy6t67
    KvDZ8ryt1VVQ7NGbLwejqIWoHAU4LTj+TwvtwLmPVwKBgGQ1D9InO1XEyJlXg9po
    Z9ELY8979DjLkp5bni5jnURU6I3XfCWuef7QjvsUh8H7zZ7PGHBgNrnezrvjworI
    NKR6N6r5YvMEgVNTfrgbTqHAvsIvkOSz6j7dHd7tWfTTawn8N6iTVlXQR4VnX/pV
    w6WFKOb8tw4LlKMM/LPTRGCd
    -----END PRIVATE KEY-----
  mongos-1-svc.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCfRYpNajV39YBR
    COxwmN8CGOFLch54ErMDBwiw9KbE9aMZofNp9/0wbNKyDWBHHTp/JWBf9TiPRJEI
    m4jgkhAtEm33BfJiZyHYiDdjWWSX4VjgS6kqm6KUxFRRFc3d6D0GIoS71fqKgfst
    J3y9HvI9Lg8B9bI6y6q3/75tdq7+ZdgFNHBxmfRgQ3ASaQ1dO2yeJ7Wz9cfmTn8E
    7bFCN0f6DQ0kpsHH5iEBTWh3aYaJYd+NzWHiZDRJgDgrf4zzDrxbIZ4J5oK4StUt
    k9/KtLLkMKh+bLFW4Dj012jRAx3gLpmshBFKDp/1UebN9z10Jlomg3GeDzteNfHp
    uejTfiGbAgMBAAECggEAAN8BKfnln6KP4xp28l61dDVCoNus7acx3MlD85IKGFsE
    BgT6S58wt4prf0HOlTiLe1xSh0kpnyRPwInbA8veDQEOzOmE+E4k/JQyJc0uQMdL
    adBqynH6lP8NApAUMGSFAOyyhLVfkMLQWKeLTRycqaz/7OcKcrvgNn5OezbJaHUB
    tLza7+naH/52soSMMPazWKuv7QVCIkoDjOSGk1+nS6YVngI7Tln4XIFcX/NP0PcU
    3Dw8yef4XzPqT6uIabI0x42O2I2XqbrC85vkfisezYDeo94Opt5bU2vnN8Gv4Jpc
    +3udNCRcMMcLMooGMc+3YRSbUjHyOk/L4j5DbW3SIQKBgQDX4IJKBoJymgW8kftW
    6Us887SPCRhSsGZIOvtd6rHqZdedO+8ePH/M+DI7iza1XerorjbCwS++6yoE0G10
    xp5hGw5/2qlCcje3sYa6reJe21ry68PofSAwADZyH8kCgjcQlsJ+N3WLL9piW9DJ
    R/d9nuf8q+p5pljk33fELqo5YwKBgQC837ttw+HV15if6gi+GkPDjpJ3lJfpZHZf
    4duIlO/bxqU3qLTLmWgzKQvyDouLTE+6k0IXVGcMGWj1R1feKPs0smwv4Xm5YMCT
    TPJADMAtLl2fJPftfIBpc4NN6JsF5IpSR/V1aMWZl9Q44VPMDpFdJqUrNSqk91SU
    O6vDGRCIaQKBgHRvb1al9C4DzRxMUJgr9JzHhZewfCH9au2CgpnBQH0AuS7haLOS
    RgwzwkRDbhqcsVsWvAqHUE1VYbB/Csp1Zm9RvJxRQAHKwSqe4eBGcVZgUcm8SEpZ
    UscRFkyvwCdOPI0CA504JHoSMWPjydUGsAJddxrdTvaWNlQcA+kYkk+pAoGAJJPf
    pH5O+i7qq+2TC93iSbkOvIHWeaivFBqVfXn6icGKtaDCgruO5nmIirQuaie5ORTT
    s9jwq/Mv1HCgn7GoFKiJMyyjejc2lFBOigDuJtHX574tFZ0K8WEhiLEHdLix4QV2
    j+peekRhITLiG56moDefvSJqw8/yXVLBDOOJxCECgYATBpfB/v4FXD3te1Dgr262
    rjcJn9DaC1O21I7VqUgAG4go7tYatB8Yan4V41G7ZzqvSQuvUce7cJGFFH28zJZM
    HsVg8ezxmzjaq4dLYfy80CWPYytlaZ6OR20ElZD19IRFDTsfhxl5avAezHlcGiPR
    4IL3jWIrop9SyRpgocBRwg==
    -----END PRIVATE KEY-----
---
# This file has been generated dynamically using generate-mongo-config-server-yml.pl, edit that file and re-run.
kind: Pod
apiVersion: v1
metadata:
  name: configurator-pod
  namespace: dev
spec:
  containers:
    - name: configurator-container
      image: mongo
      command: ['/usr/bin/perl', '/kickstart/waitscript.pl']
      volumeMounts:
        - name: kickstart-dir
          mountPath: /kickstart/
  volumes:
    - name: kickstart-dir
      configMap:
        name: rs-config
    # - name: scripts-dir
    #   persistentVolumeClaim:
    #     claimName: scripts-dir-claim
  restartPolicy: Never
  # nodeSelector:
  # role: general-services
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
                - mongo-shard-1
                - debugger
