kind: Namespace
apiVersion: v1
metadata:
  name: dev
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: config-server-1
  namespace: dev
  labels:
    purpose: database
spec:
  replicas: 1
  selector:
    matchLabels:
      role:  config-server-1
      purpose: database
  template:
    metadata:
      labels:
        role: config-server-1
        purpose: database
    spec:
      containers:
        - name: config-server-1-pod
          image: localhost:32000/mongo-cst:1.0
          imagePullPolicy: Always
          command:
            - 'sh'
            - '-c'
            - '/kickstart/mongod-launcher.sh'
          volumeMounts:
            - name: kickstart-dir
              mountPath: /kickstart/
      volumes:
        - name: kickstart-dir
          configMap:
            name: rs-config
            defaultMode: 0777
      # nodeSelector:
      #   role: general-services
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values:
                    - mongo-shard-1
                    - debugger

---
kind: Service
apiVersion: v1
metadata:
  name: config-server-svc-1
  namespace: dev
  labels:
    purpose: database
spec:
  selector:
      role: config-server-1
      purpose: database
  ports:
    - port: 27019
      targetPort: 27019
  type: ClusterIP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: config-server-2
  namespace: dev
  labels:
    purpose: database
spec:
  replicas: 1
  selector:
    matchLabels:
      role:  config-server-2
  template:
    metadata:
      labels:
        role: config-server-2
    spec:
      containers:
        - name: config-server-2-pod
          image: localhost:32000/mongo-cst:1.0
          imagePullPolicy: Always
          command:
            - 'mongod'
            - '--configsvr'
            - '--replSet'
            - 'configServerRS'
            - '--sslMode'
            - 'requireSSL'
            - '--clusterAuthMode'
            - 'x509'
            - '--sslClusterFile'
            - '/kickstart/config-server.pem'
            - '--sslPEMKeyFile'
            - '/kickstart/config-server-2.pem'
            - '--sslCAFile'
            - '/kickstart/root-ca.pem'
            - '--sslAllowInvalidCertificates'
            - '--bind_ip'
            - '*'
            # - '--dbpath'
          volumeMounts:
            - name: kickstart-dir
              mountPath: /kickstart/
      volumes:
        - name: kickstart-dir
          configMap:
            name: rs-config
            defaultMode: 0777
          # - '/var/lib/mongod'
          #      nodeSelector:
          #cloud.google.com/gke-nodepool: default-pool
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values:
                    - mongo-shard-1
                    - debugger
      # nodeSelector:
      # role: general-services

---
kind: Service
apiVersion: v1
metadata:
  name: config-server-svc-2
  namespace: dev
  labels:
    purpose: database
spec:
  selector:
      role: config-server-2
  ports:
    - port: 27019
      targetPort: 27019
  type: ClusterIP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: config-server-3
  namespace: dev
  labels:
    purpose: database
spec:
  replicas: 1
  selector:
    matchLabels:
      role:  config-server-3
  template:
    metadata:
      labels:
        role: config-server-3
    spec:
      containers:
        - name: config-server-3-pod
          image: localhost:32000/mongo-cst:1.0
          imagePullPolicy: Always
          command:
            #- 'sh'
            #- '-c'
            #- '/kickstart/mongod-launcher.sh'
            - 'mongod'
            - '--configsvr'
            - '--replSet'
            - 'configServerRS'
            - '--sslMode'
            - 'requireSSL'
            - '--clusterAuthMode'
            - 'x509'
            - '--sslClusterFile'
            - '/kickstart/config-server.pem'
            - '--sslPEMKeyFile'
            - '/kickstart/config-server-3.pem'
            - '--sslCAFile'
            - '/kickstart/root-ca.pem'
            - '--sslAllowInvalidCertificates'
            - '--bind_ip'
            - '*'
            #- '--dbpath'
            #- '/var/lib/mongod'
          volumeMounts:
            - name: kickstart-dir
              mountPath: /kickstart/
      volumes:
        - name: kickstart-dir
          configMap:
            name: rs-config
            defaultMode: 0777
            #     nodeSelector:
            #cloud.google.com/gke-nodepool: default-pool
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values:
                    - mongo-shard-1
                    - debugger

---
kind: Service
apiVersion: v1
metadata:
  name: config-server-svc-3
  namespace: dev
  labels:
    purpose: database
spec:
  selector:
      role: config-server-3
  ports:
    - port: 27019
      targetPort: 27019
  type: ClusterIP
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kickstart-dir
  namespace: dev
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: 'kickstart-disk'
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kickstart-dir-claim
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  resources:
    requests:
        storage: 10Gi
--- 
kind: ConfigMap
apiVersion: v1
metadata:
  name: rs-config
  namespace: dev
data:
  mongod-launcher.sh: |
    mongod --bind_ip_all &
    #mongo --norc --nodb --tls --tlsCertificateKeyFile /kickstart/config-server.pem --tlsCAFile /kickstart/root-ca.pem /kickstart/add-user.js
    mongosh --norc /kickstart/add-user.js
    killall mongod
    mongod --configsvr \
    --replSet configServerRS \
    --sslMode requireSSL \
    --clusterAuthMode x509 \
    --sslClusterFile /kickstart/config-server.pem \
    --sslPEMKeyFile /kickstart/config-server.pem \
    --sslCAFile /kickstart/root-ca.pem \
    --sslAllowInvalidCertificates \
    --bind_ip \*
  add-user.js: |
    // wait for mongod to be present...
    var conn;

    while(true) {
      try {
        conn = new Mongo('localhost:27017');
        break;
      } catch (Error) {
        print(Error);
      }
      sleep(100);
    }

    //conn.setReadPref('primary');

    db = conn.getDB('admin').getSiblingDB('$external');
    outcome = db.runCommand(
      {
        createUser: "CN=config-server-svc-1,OU=ExperimentClients,O=Roderick,O=BBK,L=Southminster,ST=Essex,C=GB",
        roles: [
          {role: 'userAdminAnyDatabase', db: 'admin'},
          {role: 'readWrite', db: 'test'},
          {role: 'clusterAdmin', db: 'admin'}
        ],
        writeConcern: {
          w: 'majority',
          wtimeout: 5000
        }
      }
    );
    printjson(outcome);

    outcome = db.runCommand(
      {
        createUser: "CN=mongos-1-svc,OU=ExperimentServers,O=Roderick,O=BBK,L=Southminster,ST=Essex,C=GB",
        roles: [
          {role: 'readWrite', db: 'config'},
        ],
        writeConcern: {
          w: 'majority',
          wtimeout: 5000
        }
      }
    );

    printjson(outcome);
  shard-configdb.js: |
    result = rs.initiate({
      _id: "configServerRS",
      configsvr: true,
      members: [
          { _id: 0, host: "config-server-svc-1:27019", priority: 2 },
          { _id: 1, host: "config-server-svc-2:27019", priority: 1 },
          { _id: 2, host: "config-server-svc-3:27019", priority: 1 }
      ]
    });

    printjson(result);
  waitscript.pl: |
    use Socket;

    $| = 1;

    socket(SOCKET1, PF_INET, SOCK_STREAM, (getprotobyname('tcp'))[2]);
    socket(SOCKET2, PF_INET, SOCK_STREAM, (getprotobyname('tcp'))[2]);
    socket(SOCKET3, PF_INET, SOCK_STREAM, (getprotobyname('tcp'))[2]);

    $waiting = 1;
    while ($waiting) {
      sleep 1;
      print "Attempting to connect...\n";
      
      (
        connect(SOCKET1, pack_sockaddr_in(27019, inet_aton("config-server-svc-1")))
        and connect(SOCKET2, pack_sockaddr_in(27019, inet_aton("config-server-svc-2")))
        and connect(SOCKET3, pack_sockaddr_in(27019, inet_aton("config-server-svc-3")))
      ) or next;

      $waiting = 0;
    }

    close(SOCKET1);
    close(SOCKET2);
    close(SOCKET3);

    printf "Connected!\n";

    print `mongosh --tls --sslPEMKeyFile /kickstart/config-server.pem --sslCAFile /kickstart/root-ca.pem --host config-server-svc-1 --authenticationDatabase '$external' --authenticationMechanism MONGODB-X509 --port 27019 /kickstart/shard-configdb.js `;

    exit(0);
  root-ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIEaDCCA1CgAwIBAgIUCiO3VMmsPZ/0+nJXfyGw4INxqSkwDQYJKoZIhvcNAQEL
    BQAwgdYxMzAxBgNVBAMMKlJSVCBHZW5lcmFsIFNlcnZpY2VzIENlcnRpZmljYXRl
    IEF1dGhvcml0eTEOMAwGA1UECAwFRXNzZXgxCzAJBgNVBAYTAkdCMSEwHwYJKoZI
    hvcNAQkBFhJydGltbWUwMUBiYmsuYWMudWsxJzAlBgNVBAoMHkJpcmtiZWNrLCBV
    bml2ZXJzaXR5IG9mIExvbmRvbjE2MDQGA1UECwwtU2Nob29sIG9mIENvbXB1dGlu
    ZyBhbmQgTWF0aGVtYXRpY2FsIFNjaWVuY2VzMB4XDTIzMDgyODIwMjc1NloXDTIz
    MDkyNzIwMjc1NlowgdYxMzAxBgNVBAMMKlJSVCBHZW5lcmFsIFNlcnZpY2VzIENl
    cnRpZmljYXRlIEF1dGhvcml0eTEOMAwGA1UECAwFRXNzZXgxCzAJBgNVBAYTAkdC
    MSEwHwYJKoZIhvcNAQkBFhJydGltbWUwMUBiYmsuYWMudWsxJzAlBgNVBAoMHkJp
    cmtiZWNrLCBVbml2ZXJzaXR5IG9mIExvbmRvbjE2MDQGA1UECwwtU2Nob29sIG9m
    IENvbXB1dGluZyBhbmQgTWF0aGVtYXRpY2FsIFNjaWVuY2VzMIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsmPYWq7Udpr9HqLiNaR7yO6eb95x9AhFrLfd
    4nwH0ObQLRwUugrp9WebtA5fzpGNNTz77pE27sqMMaL5G2agqCYzCWUAixFJFCce
    R+4jeHJLr0NG25p/29WWUXoE44Yj6fAXwceL/K1Jix6GHEms8HwB44o9j0A1ewxF
    RzC/4pLRsSE0bBIPAG1Mv8dgL5fHb8gwUtFw1ChLOvlE/hjQd2Y6TrwX4T632G+1
    EClHrBCJuc9ZwwoJdQGZpFj+9KuAjqGvoOOtUy9M1DELgdBhODAQ+lQNdbW4Z4jV
    OdOXyqu6VNfx/ER/ncsY61jUXht18ydysQRs/OeiDXjop+r2nwIDAQABoywwKjAJ
    BgNVHRMEAjAAMB0GA1UdDgQWBBT9bh63aMc5AQz0nZrNNlFmxyNjDDANBgkqhkiG
    9w0BAQsFAAOCAQEAVZcVSCM94QQ7udpatGOmaMikagK2uxat35a263M8zL6IGpq+
    8uqOYu9jq1tdjXf2ajV8XP4kW/Yq4gP9MfB/3oas4YHv0j6IHtC7zUE8BJq2FQUj
    mf/r1QZAS/ZBnf3yclSO/OsIM8URzoUEBb/31hJSZP38gwXdl8IAACLHkE3Ai60/
    sUv6zHQfrmjCJNgbqtee8AMf66lYvWheYvjsmBUrnYjZ3MyjwBY+MB97k0N/QGqE
    CtmLu9mzg2ZQbnjJ6doyUKSHGK1MFqnU6dPg3c7jI0BdZLR6IonjlpRzXHf4eGAO
    cjHgEhICEAH4xjLRUHxpYt0I4UzFTHtX+s2WYQ==
    -----END CERTIFICATE-----


  config-server.pem: |
    -----BEGIN CERTIFICATE-----
    MIIEYTCCA0mgAwIBAgIBCjANBgkqhkiG9w0BAQUFADCB1jEzMDEGA1UEAwwqUlJU
    IEdlbmVyYWwgU2VydmljZXMgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MQ4wDAYDVQQI
    DAVFc3NleDELMAkGA1UEBhMCR0IxITAfBgkqhkiG9w0BCQEWEnJ0aW1tZTAxQGJi
    ay5hYy51azEnMCUGA1UECgweQmlya2JlY2ssIFVuaXZlcnNpdHkgb2YgTG9uZG9u
    MTYwNAYDVQQLDC1TY2hvb2wgb2YgQ29tcHV0aW5nIGFuZCBNYXRoZW1hdGljYWwg
    U2NpZW5jZXMwHhcNMjMwODI4MjAzMjA0WhcNMzMwODI1MjAzMjA0WjCBwTEcMBoG
    A1UEAwwTY29uZmlnLXNlcnZlci1zdmMtMTEOMAwGA1UECAwFRXNzZXgxCzAJBgNV
    BAYTAkdCMSEwHwYJKoZIhvcNAQkBFhJydGltbWUwMUBiYmsuYWMudWsxKTAnBgNV
    BAoMICJCaXJrYmVjaywgVW5pdmVyc2l0eSBvZiBMb25kb24iMTYwNAYDVQQLDC1T
    Y2hvb2wgb2YgQ29tcHV0aW5nIGFuZCBNYXRoZW1hdGljYWwgU2NpZW5jZXMwggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCHHmpOoDIQQ0YF5/uY6XGoA0Ic
    166t7q0ndyI+q4sZeEz3fHKxt6FikOSKO9WlrmWhN+xs0tslrrCVHe6epnK8meFR
    rx0p1rIto+NcuJOQgpX6PopdM2jQoodq78KSrs6S6FGv7u+jDP6HBpkA4f4vymw7
    cBXKIrZ2+mTEYUz12cX9zJltAEZ89Do1Yy56+H0ByCz5ss6pEHajpCXdIrvFV9KU
    uNLUI+nypAZXe2A5qXDl9NtctWDyLe5cNWzo/ibf1uRxpwWFDuJTdKkMi4gwXbrh
    QVWIgsk3YTyfBmpxWzI3Dzi8RcBpWZT1EGq+VN2O6F/zPIuOssZd+WcTv3mfAgMB
    AAGjTTBLMAkGA1UdEwQCMAAwHQYDVR0OBBYEFDev/3Gt/R2rcJR8+cjYcxWX3iIs
    MB8GA1UdIwQYMBaAFP1uHrdoxzkBDPSdms02UWbHI2MMMA0GCSqGSIb3DQEBBQUA
    A4IBAQAXZQ/tg8CbG+E/WYz0ryumgLDeq7Cn8A5m8SyMT4mf2jLNr/WW98TTRen4
    iAhEXHdW11MCfXLt7ijDqFg8AnrXy1Q21NGXDgJTancy3HqKBef4Nsa29IcQkDqQ
    evUczx9tuYlOy6nlWxhQnJFyb3yuJ2nb7r9gqXw10EdUfemH/vU/cNh3kdTPZAai
    T4PSFHYBTlVozAAy73mKKkO/5T5SJ2SF5HqYXvce7mK41dlZ9zsf/e7glNAW4LLi
    hOSWndH+MzL/UquoQWid4bob8wNMGFwQgq3AdJKH4Bt8cAzPVPCjmSRHYDx9JoRq
    OLNYC5RG9d2/WwfLn0gRI1koEAsr
    -----END CERTIFICATE-----
  config-server-2.pem: |
    -----BEGIN CERTIFICATE-----
    MIIEYTCCA0mgAwIBAgIBDDANBgkqhkiG9w0BAQUFADCB1jEzMDEGA1UEAwwqUlJU
    IEdlbmVyYWwgU2VydmljZXMgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MQ4wDAYDVQQI
    DAVFc3NleDELMAkGA1UEBhMCR0IxITAfBgkqhkiG9w0BCQEWEnJ0aW1tZTAxQGJi
    ay5hYy51azEnMCUGA1UECgweQmlya2JlY2ssIFVuaXZlcnNpdHkgb2YgTG9uZG9u
    MTYwNAYDVQQLDC1TY2hvb2wgb2YgQ29tcHV0aW5nIGFuZCBNYXRoZW1hdGljYWwg
    U2NpZW5jZXMwHhcNMjMwODI4MjAzMjA1WhcNMzMwODI1MjAzMjA1WjCBwTEcMBoG
    A1UEAwwTY29uZmlnLXNlcnZlci1zdmMtMzEOMAwGA1UECAwFRXNzZXgxCzAJBgNV
    BAYTAkdCMSEwHwYJKoZIhvcNAQkBFhJydGltbWUwMUBiYmsuYWMudWsxKTAnBgNV
    BAoMICJCaXJrYmVjaywgVW5pdmVyc2l0eSBvZiBMb25kb24iMTYwNAYDVQQLDC1T
    Y2hvb2wgb2YgQ29tcHV0aW5nIGFuZCBNYXRoZW1hdGljYWwgU2NpZW5jZXMwggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQD03NDZVXImaj0m6u/Hlfa9xsNX
    Jget0NuXHJiugzGp30RETbvoRxOx1qZ5F1mO6UaJJVy+HAGyY8jm1JM7fGyQFA+q
    Dwq0BgVbCjqoUoqVBuY6r5vW+uxJsiXwIYjUhDDZpmhw3N7lOQlvD+9oB1wbqg5t
    bkakZMo6eCP+6WwqCvdKbMwWBTgYXa40UvnbEnXMHXmrpk3oJZObOMhpdk9CISwk
    ZX2J4W3fEktd4XY1EijTg3pa7drQ/qY+dnWs2j0pFdViX6VeS9uNYFWTXdqDClKM
    +LrNN9ohdlyH/jPf59SHBlkqWIZ8Vc+n9dGD3QOymCdccLVZQeV9PN6UsxmtAgMB
    AAGjTTBLMAkGA1UdEwQCMAAwHQYDVR0OBBYEFPjco699mz01gM7Hzo7exgbBOQV0
    MB8GA1UdIwQYMBaAFP1uHrdoxzkBDPSdms02UWbHI2MMMA0GCSqGSIb3DQEBBQUA
    A4IBAQB9h9/eJR92wKMxwghG8jDB3jaa16MTmO7vQVh63wypCUWOt43nSWhB3fdt
    FY9G9oyztRpWt7PexRd8UNZ3L8r80eN39dyJqmEyHl3Kl47sBpZch4oEtqgMzwPz
    +F8fNBCbNtfWrThO4w7vEJzzfcKvZKbmFuKa4xWK7IFWRaLYri2EadMbY9D2hbHs
    fNcz+7rI1HSbZ9xPATNsuCepJmmegPK0I5ieS8ljNfIvDp3Vqid0JX+CSbSQwVvz
    40LyQFv7BOcFjggwrn1DWfPk0quum2yJR2ZFWICPoeEmu2x4X/b0aYFOxrazxTiW
    CSY2ZnZxW2x1Su5Uqf/8/Fc+uyyb
    -----END CERTIFICATE-----
  config-server-3.pem: |
    -----BEGIN CERTIFICATE-----
    MIIEYTCCA0mgAwIBAgIBDDANBgkqhkiG9w0BAQUFADCB1jEzMDEGA1UEAwwqUlJU
    IEdlbmVyYWwgU2VydmljZXMgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MQ4wDAYDVQQI
    DAVFc3NleDELMAkGA1UEBhMCR0IxITAfBgkqhkiG9w0BCQEWEnJ0aW1tZTAxQGJi
    ay5hYy51azEnMCUGA1UECgweQmlya2JlY2ssIFVuaXZlcnNpdHkgb2YgTG9uZG9u
    MTYwNAYDVQQLDC1TY2hvb2wgb2YgQ29tcHV0aW5nIGFuZCBNYXRoZW1hdGljYWwg
    U2NpZW5jZXMwHhcNMjMwODI4MjAzMjA1WhcNMzMwODI1MjAzMjA1WjCBwTEcMBoG
    A1UEAwwTY29uZmlnLXNlcnZlci1zdmMtMzEOMAwGA1UECAwFRXNzZXgxCzAJBgNV
    BAYTAkdCMSEwHwYJKoZIhvcNAQkBFhJydGltbWUwMUBiYmsuYWMudWsxKTAnBgNV
    BAoMICJCaXJrYmVjaywgVW5pdmVyc2l0eSBvZiBMb25kb24iMTYwNAYDVQQLDC1T
    Y2hvb2wgb2YgQ29tcHV0aW5nIGFuZCBNYXRoZW1hdGljYWwgU2NpZW5jZXMwggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQD03NDZVXImaj0m6u/Hlfa9xsNX
    Jget0NuXHJiugzGp30RETbvoRxOx1qZ5F1mO6UaJJVy+HAGyY8jm1JM7fGyQFA+q
    Dwq0BgVbCjqoUoqVBuY6r5vW+uxJsiXwIYjUhDDZpmhw3N7lOQlvD+9oB1wbqg5t
    bkakZMo6eCP+6WwqCvdKbMwWBTgYXa40UvnbEnXMHXmrpk3oJZObOMhpdk9CISwk
    ZX2J4W3fEktd4XY1EijTg3pa7drQ/qY+dnWs2j0pFdViX6VeS9uNYFWTXdqDClKM
    +LrNN9ohdlyH/jPf59SHBlkqWIZ8Vc+n9dGD3QOymCdccLVZQeV9PN6UsxmtAgMB
    AAGjTTBLMAkGA1UdEwQCMAAwHQYDVR0OBBYEFPjco699mz01gM7Hzo7exgbBOQV0
    MB8GA1UdIwQYMBaAFP1uHrdoxzkBDPSdms02UWbHI2MMMA0GCSqGSIb3DQEBBQUA
    A4IBAQB9h9/eJR92wKMxwghG8jDB3jaa16MTmO7vQVh63wypCUWOt43nSWhB3fdt
    FY9G9oyztRpWt7PexRd8UNZ3L8r80eN39dyJqmEyHl3Kl47sBpZch4oEtqgMzwPz
    +F8fNBCbNtfWrThO4w7vEJzzfcKvZKbmFuKa4xWK7IFWRaLYri2EadMbY9D2hbHs
    fNcz+7rI1HSbZ9xPATNsuCepJmmegPK0I5ieS8ljNfIvDp3Vqid0JX+CSbSQwVvz
    40LyQFv7BOcFjggwrn1DWfPk0quum2yJR2ZFWICPoeEmu2x4X/b0aYFOxrazxTiW
    CSY2ZnZxW2x1Su5Uqf/8/Fc+uyyb
    -----END CERTIFICATE-----
  localhost.pem: |
    -----BEGIN CERTIFICATE-----
    MIIEVzCCAz+gAwIBAgIBEzANBgkqhkiG9w0BAQUFADCB1jEzMDEGA1UEAwwqUlJU
    IEdlbmVyYWwgU2VydmljZXMgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MQ4wDAYDVQQI
    DAVFc3NleDELMAkGA1UEBhMCR0IxITAfBgkqhkiG9w0BCQEWEnJ0aW1tZTAxQGJi
    ay5hYy51azEnMCUGA1UECgweQmlya2JlY2ssIFVuaXZlcnNpdHkgb2YgTG9uZG9u
    MTYwNAYDVQQLDC1TY2hvb2wgb2YgQ29tcHV0aW5nIGFuZCBNYXRoZW1hdGljYWwg
    U2NpZW5jZXMwHhcNMjMwODI4MjAzMjA5WhcNMzMwODI1MjAzMjA5WjCBtzESMBAG
    A1UEAwwJbG9jYWxob3N0MQ4wDAYDVQQIDAVFc3NleDELMAkGA1UEBhMCR0IxITAf
    BgkqhkiG9w0BCQEWEnJ0aW1tZTAxQGJiay5hYy51azEpMCcGA1UECgwgIkJpcmti
    ZWNrLCBVbml2ZXJzaXR5IG9mIExvbmRvbiIxNjA0BgNVBAsMLVNjaG9vbCBvZiBD
    b21wdXRpbmcgYW5kIE1hdGhlbWF0aWNhbCBTY2llbmNlczCCASIwDQYJKoZIhvcN
    AQEBBQADggEPADCCAQoCggEBAOBKd8vRKUtV3Sq8ZOVLl/dwFccuQrnmxrnqudWh
    IJUwif2ZhYp6NZVOxb8hDIolkH2y4mFn+nyOImaD1smL83DJFP9n4X//NLmMzir3
    sRBQJ2CqVRPX+zlvzeoyioPWTouKarxcqqweE9LrcmN1blNsIlpTR71FwG2dZSQm
    AAPSr0jocOYlfrMuHJKLcrvSUkkUADvptQ90c9v4iBmYjkO48B6M/UO1HHvbRE9X
    IannPElzC9tPuK3f2KELzJYFXtaaHT00kJjUmifU4xgi0M3Lp7CqG0boTZ4gvkgU
    PbgaJnoAPPjWjypb7wB7r2KfOJ+blX10leDJ53tUWvp+OJ8CAwEAAaNNMEswCQYD
    VR0TBAIwADAdBgNVHQ4EFgQUUQroNgPur8an97Y2zA8opA8K6iswHwYDVR0jBBgw
    FoAU/W4et2jHOQEM9J2azTZRZscjYwwwDQYJKoZIhvcNAQEFBQADggEBADSrVh1P
    JfGBMklGc/9AtTV38AWymlnl/u5u94pN4DCLc30aOX5MiadNtjImkYYTDBu+3b+p
    GXDKrLY60nz0l3ujUTqy7hY4qkv5mHtiONQPVC0bv+f/d0COHnn+5UiTHXDEFh8i
    S2y+b5CALiSRrFkgs5Nks/k/5hSPe1LDC5cs+7oeKEKiOK4T/Bow51gNLkzlnkUf
    VnwlkDndFmQXQcSJdQmcQm//aYdgapNsxyhDJy3+RiexGBP2Id9DEwVtlSHV7Syp
    EjTPjguFhIHCQGHXm6ae1khjJkZTw3HqFOGDouHlHBq36zNkDG2m+HScxkntrxm2
    hORDkWrNarnskYY=
    -----END CERTIFICATE-----
---
kind: Pod
apiVersion: v1
metadata:
  name: configurator-pod
  namespace: dev
spec:
  containers:
    - name: configurator-container
      image: mongo
      command: ['/usr/bin/perl', '/kickstart/waitscript.pl']
      volumeMounts:
        - name: kickstart-dir
          mountPath: /kickstart/
  volumes:
    - name: kickstart-dir
      configMap:
        name: rs-config
    # - name: scripts-dir
    #   persistentVolumeClaim:
    #     claimName: scripts-dir-claim
  restartPolicy: Never
  # nodeSelector:
  # role: general-services
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
                - mongo-shard-1
                - debugger
