---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cm
  namespace: dev
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'experiment'
        scrape_interval: 5s
        static_configs:
          - targets:
              - arnold-pri:9091
              - arnold-sec-1:9091
              - arnold-sec-2:9091
            labels:
              group: experiment-1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      role: prometheus
  template:
    metadata:
      labels:
        role: prometheus
    spec:
      containers:
        - name: prometheus-server
          image: prom/prometheus
          command:
            - '/bin/prometheus'
            - '--config.file=/config/prometheus.yml'
          ports:
            - name: prometheus
              containerPort: 9090
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /config
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-cm
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: dev
spec:
  selector:
    role: prometheus
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090