---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cm
  namespace: dev
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'experiment'
        scrape_interval: 5s
        static_configs:
          - targets:
              - arnold-pri:9091
              - arnold-sec-1:9091
              - arnold-sec-2:9091
              - bairstow-pri:9091
              - bairstow-sec-1:9091
              - bairstow-sec-2:9091
              - calvin-pri:9091
              - calvin-sec-1:9091
              - calvin-sec-2:9091
              - duncan-pri:9091
              - duncan-sec-1:9091
              - duncan-sec-2:9091
              - elliot-pri:9091
              - elliot-sec-1:9091
              - elliot-sec-2:9091
              - consumer-0:9091
              - consumer-1:9091
              - consumer-2:9091
              - consumer-3:9091
              - consumer-4:9091
              - consumer-5:9091
              - consumer-6:9091
              - consumer-7:9091
              - consumer-8:9091
              - consumer-9:9091
              - consumer-10:9091
              - consumer-11:9091
              - consumer-12:9091
              - consumer-13:9091
              - consumer-14:9091
              - consumer-15:9091
            labels:
              group: experiment-1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      role: prometheus
  template:
    metadata:
      labels:
        role: prometheus
    spec:
      containers:
        - name: prometheus-server
          image: prom/prometheus
          command:
            - '/bin/prometheus'
            - '--config.file=/config/prometheus.yml'
            - '--storage.tsdb.path=/data/'
          ports:
            - name: prometheus
              containerPort: 9090
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /config
              name: config-volume
            - name: data-volume
              mountPath: /data/
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-cm
        - name: data-volume
          hostPath:
            path: /home/roderick/experiment-data
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    role: prometheus
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
      # nodePort: 30190
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: dev
spec:
  selector:
    matchLabels:
      role: grafana
  replicas: 1
  template:
    metadata:
      labels:
        role: grafana
    spec:
      containers:
        - name: grafana-server
          image: grafana/grafana
          ports:
            - name: grafana
              containerPort: 3000
          env:
            - name: GF_DATABASE_PATH
              value: /data/grafana
          volumeMounts:
          - name: data-volume
            mountPath: /data/
      volumes:
        - name: data-volume
          hostPath:
            path: /home/roderick/experiment-data
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    role: grafana
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
