tasks:
  - name: Unload the cluster
    become: false
    ignore_errors: true
    shell: |
      microk8s kubectl delete -f /home/roderick/testbed/compute-layer/copmuter-layer.yml;\
      microk8s kubectl delete -f /home/roderick/testbed/mongo-config-svc.yml
