---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kafka-topic-server
  labels:
    purpose: topic-server
    role: kafka
  namespace: dev
spec:
  selector:
    matchLabels:
      role: kafka
      purpose: topic-server
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        purpose: topic-server
        role: kafka
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - image: eu.gcr.io/research-310823/kafka-topic-server:0.1
          name: kafka-topic-server
          ports:
            - containerPort: 9092
            - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-topic-server
  namespace: dev
spec:
  selector:
    role: kafka-topic-server
  ports:
    - port: 9092
      targetPort: 9092
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-0
  labels:
    purpose: consumer
  namespace: dev
spec:
  selector:
    matchLabels:
      purpose: consumer
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        purpose: consumer
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - image: eu.gcr.io/research-310823/operator:1.0
          name: consumer-0-container
          env:
            - {name: ROLE, value: consumer}
            - {name: TOPIC, value:  test-0}
          ports:
            - containerPort: 9091