version: "3.8"
services:
  producer-shell:
    image: operator:1.0
    build: .
    environment:
      - ROLE=producer-shell
  consumer:
    image: operator:1.0
    build: .
    environment:
      - ROLE=consumer
      - TOPIC=test-1
      - TRUSTSTORE_PATH=/root/mandelbrot-generator/test.ts
      - KEYSTORE_PATH=/root/mandelbrot-generator/test.ks
    volumes:
      - .:/app
  kafka-topic-server:
    image: kafka-topic-server:0.1
    build: ./kafka
    env_file: ./kafka/.env
    ports:
      - "9092:9092"
