version: "3.9"
services:
  operator:
    image: operator:1.0
    build: .
    environment:
      - ROLE=consumer
      - TOPIC=test-1
    volumes:
      - .:/app
  kafka-topic-server:
    image: kafka-topic-server:0.1
    build: ./kafka
    env_file: ./kafka/.env
    ports:
      - "9092:9092"
